"""Patient-row pyarrow schema, derived from the GDC Data Dictionary.

## Provenance

These field lists are exhaustive snapshots from the gdcdictionary YAML files
(https://github.com/NCI-GDC/gdcdictionary), with a few system properties
(state / created_datetime / updated_datetime / project_id / relationship
pointers) excluded. We bake them in statically so the parquet schema is
deterministic at build time rather than subject to live-API drift.

Two related artifacts:

  - **This file** is the build-time schema we write parquet against. The
    clinical entity sections were generated by
    `scripts/regenerate_clinical_fields.py /path/to/gdcdictionary` and
    pasted in. Re-run when the dictionary changes upstream.
  - **Per-fetch dictionary snapshot** at
    `<data-dir>/raw/gdc_dictionary.<major>.<minor>.json` is the live
    dictionary the GDC was serving when the data was fetched. Its SHA-256 is
    recorded in each project's `gdc_status.json`. This is the authoritative
    "what was the dictionary when this data shipped" record; if it diverges
    from the static schema in this file, regenerate.

Type assignments come from each property's `type` (or `oneOf`) declaration;
enums map to `pa.string()`. The MAF-derived `MUTATION_FIELDS` and TSV-derived
`EXPRESSION_FIELDS` follow the same all-fields-preserved principle for their
respective formats.
"""

from __future__ import annotations

import pyarrow as pa

# ---------------------------------------------------------------------------
# Clinical entities (case → demographic / diagnoses / follow_ups / etc.)
# Field lists generated from gdcdictionary YAML; ordered by dependency so
# parents reference their children's *_FIELDS by name.
# ---------------------------------------------------------------------------

DEMOGRAPHIC_FIELDS: list[pa.Field] = [
    pa.field("demographic_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("age_at_index", pa.int64()),
    pa.field("age_is_obfuscated", pa.bool_()),
    pa.field("cause_of_death", pa.string()),
    pa.field("cause_of_death_source", pa.string()),
    pa.field("country_of_birth", pa.string()),
    pa.field("country_of_residence_at_enrollment", pa.string()),
    pa.field("days_to_birth", pa.int64()),
    pa.field("days_to_death", pa.int64()),
    pa.field("education_level", pa.string()),
    pa.field("ethnicity", pa.string()),
    pa.field("marital_status", pa.string()),
    pa.field("occupation_duration_years", pa.int64()),
    pa.field("population_group", pa.string()),
    pa.field("race", pa.string()),
    pa.field("sex_at_birth", pa.string()),
    pa.field("vital_status", pa.string()),
    pa.field("year_of_birth", pa.int64()),
    pa.field("year_of_birth_range", pa.string()),
    pa.field("year_of_death", pa.int64()),
]

TREATMENT_FIELDS: list[pa.Field] = [
    pa.field("treatment_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("chemo_concurrent_to_radiation", pa.string()),
    pa.field("clinical_trial_indicator", pa.string()),
    pa.field("course_number", pa.float64()),
    pa.field("days_to_treatment_end", pa.int64()),
    pa.field("days_to_treatment_start", pa.int64()),
    pa.field("drug_category", pa.string()),
    pa.field("embolic_agent", pa.string()),
    pa.field("initial_disease_status", pa.string()),
    pa.field("lesions_treated_number", pa.float64()),
    pa.field("margin_distance", pa.float64()),
    pa.field("margin_status", pa.string()),
    pa.field("margins_involved_site", pa.string()),
    pa.field("number_of_cycles", pa.int64()),
    pa.field("number_of_fractions", pa.float64()),
    pa.field("prescribed_dose", pa.float64()),
    pa.field("prescribed_dose_units", pa.string()),
    pa.field("pretreatment", pa.string()),
    pa.field("protocol_identifier", pa.string()),
    pa.field("radiosensitizing_agent", pa.string()),
    pa.field("reason_treatment_ended", pa.string()),
    pa.field("reason_treatment_not_given", pa.string()),
    pa.field("regimen_or_line_of_therapy", pa.string()),
    pa.field("residual_disease", pa.string()),
    pa.field("route_of_administration", pa.list_(pa.string())),
    pa.field("therapeutic_agents", pa.string()),
    pa.field("therapeutic_levels_achieved", pa.string()),
    pa.field("therapeutic_target_level", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("treatment_anatomic_sites", pa.list_(pa.string())),
    pa.field("treatment_dose", pa.int64()),
    pa.field("treatment_dose_max", pa.float64()),
    pa.field("treatment_dose_units", pa.string()),
    pa.field("treatment_duration", pa.int64()),
    pa.field("treatment_effect", pa.string()),
    pa.field("treatment_effect_indicator", pa.string()),
    pa.field("treatment_frequency", pa.string()),
    pa.field("treatment_intent_type", pa.string()),
    pa.field("treatment_or_therapy", pa.string()),
    pa.field("treatment_outcome", pa.string()),
    pa.field("treatment_outcome_duration", pa.int64()),
    pa.field("treatment_type", pa.string()),
    pa.field("treatment_type_administered", pa.string()),
]

DIAGNOSIS_FIELDS: list[pa.Field] = [
    pa.field("diagnosis_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("adrenal_hormone", pa.string()),
    pa.field("age_at_diagnosis", pa.int64()),
    pa.field("ajcc_clinical_m", pa.string()),
    pa.field("ajcc_clinical_n", pa.string()),
    pa.field("ajcc_clinical_stage", pa.string()),
    pa.field("ajcc_clinical_t", pa.string()),
    pa.field("ajcc_pathologic_m", pa.string()),
    pa.field("ajcc_pathologic_n", pa.string()),
    pa.field("ajcc_pathologic_stage", pa.string()),
    pa.field("ajcc_pathologic_t", pa.string()),
    pa.field("ajcc_serum_tumor_markers", pa.string()),
    pa.field("ajcc_staging_system_edition", pa.string()),
    pa.field("ann_arbor_b_symptoms", pa.string()),
    pa.field("ann_arbor_b_symptoms_described", pa.string()),
    pa.field("ann_arbor_b_symptoms_described_array", pa.list_(pa.string())),
    pa.field("ann_arbor_clinical_stage", pa.string()),
    pa.field("ann_arbor_extranodal_involvement", pa.string()),
    pa.field("ann_arbor_pathologic_stage", pa.string()),
    pa.field("best_overall_response", pa.string()),
    pa.field("burkitt_lymphoma_clinical_variant", pa.string()),
    pa.field("calgb_risk_group", pa.string()),
    pa.field("cancer_detection_method", pa.string()),
    pa.field("child_pugh_classification", pa.string()),
    pa.field("clark_level", pa.string()),
    pa.field("classification_of_tumor", pa.string()),
    pa.field("cog_liver_stage", pa.string()),
    pa.field("cog_neuroblastoma_risk_group", pa.string()),
    pa.field("cog_renal_stage", pa.string()),
    pa.field("cog_rhabdomyosarcoma_risk_group", pa.string()),
    pa.field("contiguous_organ_invaded", pa.string()),
    pa.field("days_to_best_overall_response", pa.int64()),
    pa.field("days_to_diagnosis", pa.int64()),
    pa.field("days_to_last_follow_up", pa.float64()),
    pa.field("days_to_last_known_disease_status", pa.float64()),
    pa.field("days_to_recurrence", pa.float64()),
    pa.field("diagnosis_is_primary_disease", pa.bool_()),
    pa.field("double_expressor_lymphoma", pa.string()),
    pa.field("double_hit_lymphoma", pa.string()),
    pa.field("eln_risk_classification", pa.string()),
    pa.field("enneking_msts_grade", pa.string()),
    pa.field("enneking_msts_metastasis", pa.string()),
    pa.field("enneking_msts_stage", pa.string()),
    pa.field("enneking_msts_tumor_site", pa.string()),
    pa.field("ensat_clinical_m", pa.string()),
    pa.field("ensat_pathologic_n", pa.string()),
    pa.field("ensat_pathologic_stage", pa.string()),
    pa.field("ensat_pathologic_t", pa.string()),
    pa.field("esophageal_columnar_dysplasia_degree", pa.string()),
    pa.field("esophageal_columnar_metaplasia_present", pa.string()),
    pa.field("fab_morphology_code", pa.string()),
    pa.field("figo_stage", pa.string()),
    pa.field("figo_staging_edition_year", pa.string()),
    pa.field("first_symptom_longest_duration", pa.string()),
    pa.field("first_symptom_prior_to_diagnosis", pa.string()),
    pa.field("gastric_esophageal_junction_involvement", pa.string()),
    pa.field("gleason_grade_group", pa.string()),
    pa.field("gleason_grade_tertiary", pa.string()),
    pa.field("gleason_patterns_percent", pa.int64()),
    pa.field("gleason_score", pa.int64()),
    pa.field("goblet_cells_columnar_mucosa_present", pa.string()),
    pa.field("icd_10_code", pa.string()),
    pa.field("igcccg_stage", pa.string()),
    pa.field("inpc_grade", pa.string()),
    pa.field("inpc_histologic_group", pa.string()),
    pa.field("inrg_stage", pa.string()),
    pa.field("inss_stage", pa.string()),
    pa.field("international_prognostic_index", pa.string()),
    pa.field("irs_group", pa.string()),
    pa.field("irs_stage", pa.string()),
    pa.field("ishak_fibrosis_score", pa.string()),
    pa.field("iss_stage", pa.string()),
    pa.field("last_known_disease_status", pa.string()),
    pa.field("laterality", pa.string()),
    pa.field("margin_distance", pa.float64()),
    pa.field("margins_involved_site", pa.string()),
    pa.field("masaoka_stage", pa.string()),
    pa.field("max_tumor_bulk_site", pa.string()),
    pa.field("medulloblastoma_molecular_classification", pa.string()),
    pa.field("melanoma_known_primary", pa.string()),
    pa.field("metastasis_at_diagnosis", pa.string()),
    pa.field("method_of_diagnosis", pa.string()),
    pa.field("mitosis_karyorrhexis_index", pa.string()),
    pa.field("morphology", pa.string()),
    pa.field("ovarian_specimen_status", pa.string()),
    pa.field("ovarian_surface_involvement", pa.string()),
    pa.field("pediatric_kidney_staging", pa.string()),
    pa.field("peritoneal_fluid_cytological_status", pa.string()),
    pa.field("primary_diagnosis", pa.string()),
    pa.field("primary_gleason_grade", pa.string()),
    pa.field("prior_malignancy", pa.string()),
    pa.field("prior_treatment", pa.string()),
    pa.field("progression_or_recurrence", pa.string()),
    pa.field("residual_disease", pa.string()),
    pa.field("satellite_nodule_present", pa.string()),
    pa.field("secondary_gleason_grade", pa.string()),
    pa.field("site_of_resection_or_biopsy", pa.string()),
    pa.field("sites_of_involvement", pa.list_(pa.string())),
    pa.field("sites_of_involvement_count", pa.int64()),
    pa.field("supratentorial_localization", pa.string()),
    pa.field("synchronous_malignancy", pa.string()),
    pa.field("tissue_or_organ_of_origin", pa.string()),
    pa.field("tumor_burden", pa.float64()),
    pa.field("tumor_confined_to_organ_of_origin", pa.string()),
    pa.field("tumor_depth", pa.float64()),
    pa.field("tumor_focality", pa.string()),
    pa.field("tumor_grade", pa.string()),
    pa.field("tumor_grade_category", pa.string()),
    pa.field("tumor_of_origin", pa.string()),
    pa.field("tumor_regression_grade", pa.string()),
    pa.field("uicc_clinical_m", pa.string()),
    pa.field("uicc_clinical_n", pa.string()),
    pa.field("uicc_clinical_stage", pa.string()),
    pa.field("uicc_clinical_t", pa.string()),
    pa.field("uicc_pathologic_m", pa.string()),
    pa.field("uicc_pathologic_n", pa.string()),
    pa.field("uicc_pathologic_stage", pa.string()),
    pa.field("uicc_pathologic_t", pa.string()),
    pa.field("uicc_staging_system_edition", pa.string()),
    pa.field("ulceration_indicator", pa.string()),
    pa.field("weiss_assessment_findings", pa.list_(pa.string())),
    pa.field("weiss_assessment_score", pa.string()),
    pa.field("who_cns_grade", pa.string()),
    pa.field("who_nte_grade", pa.string()),
    pa.field("wilms_tumor_histologic_subtype", pa.string()),
    pa.field("year_of_diagnosis", pa.int64()),
    pa.field("treatments", pa.list_(pa.struct(TREATMENT_FIELDS))),
]

FOLLOW_UP_FIELDS: list[pa.Field] = [
    pa.field("follow_up_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("adverse_event", pa.string()),
    pa.field("adverse_event_grade", pa.string()),
    pa.field("barretts_esophagus_goblet_cells_present", pa.string()),
    pa.field("cause_of_response", pa.string()),
    pa.field("days_to_adverse_event", pa.int64()),
    pa.field("days_to_first_event", pa.int64()),
    pa.field("days_to_follow_up", pa.int64()),
    pa.field("days_to_imaging", pa.int64()),
    pa.field("days_to_progression", pa.int64()),
    pa.field("days_to_progression_free", pa.int64()),
    pa.field("days_to_recurrence", pa.int64()),
    pa.field("discontiguous_lesion_count", pa.int64()),
    pa.field("disease_response", pa.string()),
    pa.field("ecog_performance_status", pa.string()),
    pa.field("evidence_of_progression_type", pa.string()),
    pa.field("evidence_of_recurrence_type", pa.string()),
    pa.field("first_event", pa.string()),
    pa.field("histologic_progression", pa.string()),
    pa.field("history_of_tumor", pa.string()),
    pa.field("history_of_tumor_type", pa.string()),
    pa.field("hormone_replacement_therapy_type", pa.string()),
    pa.field("imaging_anatomic_site", pa.list_(pa.string())),
    pa.field("imaging_findings", pa.string()),
    pa.field("imaging_result", pa.string()),
    pa.field("imaging_suv", pa.float64()),
    pa.field("imaging_suv_max", pa.float64()),
    pa.field("imaging_type", pa.string()),
    pa.field("karnofsky_performance_status", pa.string()),
    pa.field("peritoneal_washing_results", pa.string()),
    pa.field("procedures_performed", pa.string()),
    pa.field("progression_or_recurrence", pa.string()),
    pa.field("progression_or_recurrence_anatomic_site", pa.string()),
    pa.field("progression_or_recurrence_type", pa.string()),
    pa.field("recist_targeted_regions_number", pa.int64()),
    pa.field("recist_targeted_regions_sum", pa.float64()),
    pa.field("scan_tracer_used", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("treatment_emergent_adverse_event", pa.string()),
    pa.field("year_of_follow_up", pa.int64()),
]

EXPOSURE_FIELDS: list[pa.Field] = [
    pa.field("exposure_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("age_at_last_exposure", pa.int64()),
    pa.field("age_at_onset", pa.int64()),
    pa.field("alcohol_days_per_week", pa.float64()),
    pa.field("alcohol_drinks_per_day", pa.float64()),
    pa.field("alcohol_frequency", pa.string()),
    pa.field("alcohol_history", pa.string()),
    pa.field("alcohol_intensity", pa.string()),
    pa.field("alcohol_type", pa.string()),
    pa.field("asbestos_exposure_type", pa.string()),
    pa.field("chemical_exposure_type", pa.list_(pa.string())),
    pa.field("cigarettes_per_day", pa.float64()),
    pa.field("environmental_tobacco_smoke_exposure", pa.string()),
    pa.field("exposure_duration", pa.string()),
    pa.field("exposure_duration_hrs_per_day", pa.float64()),
    pa.field("exposure_duration_years", pa.int64()),
    pa.field("exposure_source", pa.string()),
    pa.field("exposure_type", pa.string()),
    pa.field("occupation_duration_years", pa.int64()),
    pa.field("occupation_type", pa.list_(pa.string())),
    pa.field("pack_years_smoked", pa.float64()),
    pa.field("parent_with_radiation_exposure", pa.string()),
    pa.field("secondhand_smoke_as_child", pa.string()),
    pa.field("smoking_frequency", pa.string()),
    pa.field("time_between_waking_and_first_smoke", pa.string()),
    pa.field("tobacco_smoking_onset_year", pa.int64()),
    pa.field("tobacco_smoking_quit_year", pa.int64()),
    pa.field("tobacco_smoking_status", pa.string()),
    pa.field("type_of_smoke_exposure", pa.string()),
    pa.field("type_of_tobacco_used", pa.string()),
    pa.field("use_per_day", pa.float64()),
]

FAMILY_HISTORY_FIELDS: list[pa.Field] = [
    pa.field("family_history_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("relationship_age_at_diagnosis", pa.float64()),
    pa.field("relationship_primary_diagnosis", pa.string()),
    pa.field("relationship_sex_at_birth", pa.string()),
    pa.field("relationship_type", pa.string()),
    pa.field("relative_deceased", pa.string()),
    pa.field("relative_smoker", pa.string()),
    pa.field("relative_with_cancer_history", pa.string()),
    pa.field("relatives_with_cancer_history_count", pa.int64()),
]

# ---------------------------------------------------------------------------
# Biospecimen hierarchy: aliquot ⊂ analyte ⊂ portion ⊂ sample
# Preserved verbatim from the GDC dictionary.
# ---------------------------------------------------------------------------

ALIQUOT_FIELDS: list[pa.Field] = [
    pa.field("aliquot_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("aliquot_quantity", pa.float64()),
    pa.field("aliquot_volume", pa.float64()),
    pa.field("amount", pa.float64()),
    pa.field("analyte_type", pa.string()),
    pa.field("centers", pa.string()),
    pa.field("concentration", pa.float64()),
    pa.field("no_matched_normal_low_pass_wgs", pa.bool_()),
    pa.field("no_matched_normal_targeted_sequencing", pa.bool_()),
    pa.field("no_matched_normal_wgs", pa.bool_()),
    pa.field("no_matched_normal_wxs", pa.bool_()),
    pa.field("selected_normal_low_pass_wgs", pa.bool_()),
    pa.field("selected_normal_targeted_sequencing", pa.bool_()),
    pa.field("selected_normal_wgs", pa.bool_()),
    pa.field("selected_normal_wxs", pa.bool_()),
    pa.field("source_center", pa.string()),
]

ANALYTE_FIELDS: list[pa.Field] = [
    pa.field("analyte_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("a260_a280_ratio", pa.float64()),
    pa.field("amount", pa.float64()),
    pa.field("analyte_quantity", pa.float64()),
    pa.field("analyte_type", pa.string()),  # "DNA" or "RNA" — drives which assays apply
    pa.field("analyte_volume", pa.float64()),
    pa.field("concentration", pa.float64()),
    pa.field("dna_integrity_number", pa.float64()),
    pa.field("experimental_protocol_type", pa.string()),
    pa.field("normal_tumor_genotype_snp_match", pa.string()),
    pa.field("ribosomal_rna_28s_18s_ratio", pa.float64()),
    pa.field("rna_integrity_number", pa.float64()),
    pa.field("spectrophotometer_method", pa.string()),
    pa.field("well_number", pa.string()),
    pa.field("aliquots", pa.list_(pa.struct(ALIQUOT_FIELDS))),
]

PORTION_FIELDS: list[pa.Field] = [
    pa.field("portion_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("centers", pa.string()),
    pa.field("creation_datetime", pa.float64()),
    pa.field("is_ffpe", pa.bool_()),  # FFPE-fixed tissue behaves differently in many assays
    pa.field("portion_number", pa.string()),
    pa.field("weight", pa.float64()),
    pa.field("analytes", pa.list_(pa.struct(ANALYTE_FIELDS))),
]

SAMPLE_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("biospecimen_anatomic_site", pa.string()),
    pa.field("biospecimen_laterality", pa.string()),
    pa.field("catalog_reference", pa.string()),
    pa.field("current_weight", pa.float64()),
    # days_to_collection: per GDC dictionary, days from index date to BCR
    # receipt of the case's biospecimen package. Per-case batch event (the
    # same value typically applies to all of a case's samples). Can exceed
    # days_to_death because shipping/accession lags death.
    pa.field("days_to_collection", pa.int64()),
    # days_to_sample_procurement: per GDC dictionary, days from index date to
    # the surgical/biopsy event that produced this specific sample. Sparsely
    # populated in TCGA but the right field for true clinical timing.
    pa.field("days_to_sample_procurement", pa.int64()),
    pa.field("diagnosis_pathologically_confirmed", pa.string()),
    pa.field("distance_normal_to_tumor", pa.string()),
    pa.field("distributor_reference", pa.string()),
    pa.field("freezing_method", pa.string()),
    pa.field("growth_rate", pa.int64()),
    pa.field("initial_weight", pa.float64()),
    pa.field("intermediate_dimension", pa.float64()),
    pa.field("longest_dimension", pa.float64()),
    pa.field("method_of_sample_procurement", pa.string()),
    pa.field("parent_samples", pa.string()),
    pa.field("passage_count", pa.int64()),
    pa.field("pathology_report_uuid", pa.string()),
    pa.field("preservation_method", pa.string()),
    pa.field("sample_ordinal", pa.int64()),
    pa.field("sample_type", pa.string()),
    pa.field("shortest_dimension", pa.float64()),
    pa.field("specimen_type", pa.string()),
    pa.field("time_between_clamping_and_freezing", pa.float64()),
    pa.field("time_between_excision_and_freezing", pa.float64()),
    pa.field("tissue_collection_type", pa.string()),
    pa.field("tissue_type", pa.string()),
    pa.field("tumor_descriptor", pa.string()),
    pa.field("portions", pa.list_(pa.struct(PORTION_FIELDS))),
]

# ---------------------------------------------------------------------------
# Molecular: Masked Somatic Mutation (MAF) — all 140 columns + 3 FK fields
# ---------------------------------------------------------------------------

# Full GDC MAF v1.0.0 column ordering (140 cols).
_MAF_COLUMNS: list[str] = [
    "Hugo_Symbol",
    "Entrez_Gene_Id",
    "Center",
    "NCBI_Build",
    "Chromosome",
    "Start_Position",
    "End_Position",
    "Strand",
    "Variant_Classification",
    "Variant_Type",
    "Reference_Allele",
    "Tumor_Seq_Allele1",
    "Tumor_Seq_Allele2",
    "dbSNP_RS",
    "dbSNP_Val_Status",
    "Tumor_Sample_Barcode",
    "Matched_Norm_Sample_Barcode",
    "Match_Norm_Seq_Allele1",
    "Match_Norm_Seq_Allele2",
    "Tumor_Validation_Allele1",
    "Tumor_Validation_Allele2",
    "Match_Norm_Validation_Allele1",
    "Match_Norm_Validation_Allele2",
    "Verification_Status",
    "Validation_Status",
    "Mutation_Status",
    "Sequencing_Phase",
    "Sequence_Source",
    "Validation_Method",
    "Score",
    "BAM_File",
    "Sequencer",
    # Despite the names, *_Sample_UUID columns are *aliquot* UUIDs per GDC spec.
    "Tumor_Sample_UUID",
    "Matched_Norm_Sample_UUID",
    "HGVSc",
    "HGVSp",
    "HGVSp_Short",
    "Transcript_ID",
    "Exon_Number",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "all_effects",
    "Allele",
    "Gene",
    "Feature",
    "Feature_type",
    "One_Consequence",
    "Consequence",
    "cDNA_position",
    "CDS_position",
    "Protein_position",
    "Amino_acids",
    "Codons",
    "Existing_variation",
    "DISTANCE",
    "TRANSCRIPT_STRAND",
    "SYMBOL",
    "SYMBOL_SOURCE",
    "HGNC_ID",
    "BIOTYPE",
    "CANONICAL",
    "CCDS",
    "ENSP",
    "SWISSPROT",
    "TREMBL",
    "UNIPARC",
    "UNIPROT_ISOFORM",
    "RefSeq",
    "MANE",
    "APPRIS",
    "FLAGS",
    "SIFT",
    "PolyPhen",
    "EXON",
    "INTRON",
    "DOMAINS",
    "1000G_AF",
    "1000G_AFR_AF",
    "1000G_AMR_AF",
    "1000G_EAS_AF",
    "1000G_EUR_AF",
    "1000G_SAS_AF",
    "ESP_AA_AF",
    "ESP_EA_AF",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "MAX_AF",
    "MAX_AF_POPS",
    "gnomAD_non_cancer_AF",
    "gnomAD_non_cancer_AFR_AF",
    "gnomAD_non_cancer_AMI_AF",
    "gnomAD_non_cancer_AMR_AF",
    "gnomAD_non_cancer_ASJ_AF",
    "gnomAD_non_cancer_EAS_AF",
    "gnomAD_non_cancer_FIN_AF",
    "gnomAD_non_cancer_MID_AF",
    "gnomAD_non_cancer_NFE_AF",
    "gnomAD_non_cancer_OTH_AF",
    "gnomAD_non_cancer_SAS_AF",
    "gnomAD_non_cancer_MAX_AF_adj",
    "gnomAD_non_cancer_MAX_AF_POPS_adj",
    "CLIN_SIG",
    "SOMATIC",
    "PUBMED",
    "TRANSCRIPTION_FACTORS",
    "MOTIF_NAME",
    "MOTIF_POS",
    "HIGH_INF_POS",
    "MOTIF_SCORE_CHANGE",
    "miRNA",
    "IMPACT",
    "PICK",
    "VARIANT_CLASS",
    "TSL",
    "HGVS_OFFSET",
    "PHENO",
    "GENE_PHENO",
    "CONTEXT",
    "tumor_bam_uuid",
    "normal_bam_uuid",
    "case_id",
    "GDC_FILTER",
    "COSMIC",
    "hotspot",
    "RNA_Support",
    "RNA_depth",
    "RNA_ref_count",
    "RNA_alt_count",
    "callers",
]
assert len(_MAF_COLUMNS) == 140, f"expected 140 MAF columns, got {len(_MAF_COLUMNS)}"

_MAF_INT_COLS: set[str] = {
    "Entrez_Gene_Id",
    "Start_Position",
    "End_Position",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "RNA_depth",
    "RNA_ref_count",
    "RNA_alt_count",
}
_MAF_FLOAT_COLS: set[str] = {
    "1000G_AF",
    "1000G_AFR_AF",
    "1000G_AMR_AF",
    "1000G_EAS_AF",
    "1000G_EUR_AF",
    "1000G_SAS_AF",
    "ESP_AA_AF",
    "ESP_EA_AF",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "MAX_AF",
    "gnomAD_non_cancer_AF",
    "gnomAD_non_cancer_AFR_AF",
    "gnomAD_non_cancer_AMI_AF",
    "gnomAD_non_cancer_AMR_AF",
    "gnomAD_non_cancer_ASJ_AF",
    "gnomAD_non_cancer_EAS_AF",
    "gnomAD_non_cancer_FIN_AF",
    "gnomAD_non_cancer_MID_AF",
    "gnomAD_non_cancer_NFE_AF",
    "gnomAD_non_cancer_OTH_AF",
    "gnomAD_non_cancer_SAS_AF",
    "gnomAD_non_cancer_MAX_AF_adj",
    "MOTIF_SCORE_CHANGE",
}


def _maf_field(name: str) -> pa.Field:
    if name in _MAF_INT_COLS:
        return pa.field(name, pa.int64())
    if name in _MAF_FLOAT_COLS:
        return pa.field(name, pa.float64())
    return pa.field(name, pa.string())


# Three sample/aliquot FK fields prepended; all 140 MAF columns follow in MAF
# order. The MAF already carries case_id (col 132) and the aliquot UUIDs
# (Tumor_Sample_UUID, Matched_Norm_Sample_UUID) — we don't duplicate those.
MUTATION_FIELDS: list[pa.Field] = [
    pa.field("tumor_sample_id", pa.string()),
    pa.field("matched_normal_sample_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    *[_maf_field(name) for name in _MAF_COLUMNS],
]

# ---------------------------------------------------------------------------
# Molecular: Gene Expression Quantification (RNA-Seq STAR counts)
# Struct-of-arrays inside list-of-struct; field names match GDC TSV columns.
# stranded_first/stranded_second dropped — the GDC pipeline treats all reads
# as unstranded for cross-sample harmonization (see expression.py docstring).
# ---------------------------------------------------------------------------

EXPRESSION_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    # QC summary metrics (lifted from N_* rows; using unstranded counts)
    pa.field("N_unmapped", pa.int64()),
    pa.field("N_multimapping", pa.int64()),
    pa.field("N_noFeature", pa.int64()),
    pa.field("N_ambiguous", pa.int64()),
    # Gene metadata — GENCODE v36, version suffix preserved (e.g. ENSG...15)
    pa.field("gene_id", pa.list_(pa.string())),
    pa.field("gene_name", pa.list_(pa.string())),
    pa.field("gene_type", pa.list_(pa.string())),
    # Numeric value arrays — index-aligned to gene_id
    pa.field("unstranded", pa.list_(pa.int64())),
    pa.field("tpm_unstranded", pa.list_(pa.float64())),
    pa.field("fpkm_unstranded", pa.list_(pa.float64())),
    pa.field("fpkm_uq_unstranded", pa.list_(pa.float64())),
]

# ---------------------------------------------------------------------------
# Clinical: Pathology Report (the BCR-scanned PDF, shipped verbatim)
#
# Unlike every other modality here, the payload is not a parsed table — it's
# the source document itself. TCGA pathology reports are scanned PDFs; GDC
# ships them open-access with patient identifiers redacted out of the page
# image. We carry the bytes unmodified in `pdf_bytes` rather than a text
# extraction, because any parse is a lossy, tool-and-version-specific
# derivation that consumers should be able to redo (and disagree with)
# without re-downloading 2.6 GB from GDC. A canonical parse, if we add one,
# belongs in its own clearly-labeled column alongside these bytes.
#
# `pathology_report_uuid` is parsed out of the GDC file name
# (`<case_submitter_id>.<REPORT_UUID>.PDF`) and is the same value the GDC
# already reports on `sample.pathology_report_uuid` — so a report joins to
# its sample through a key the dataset has always carried.
# ---------------------------------------------------------------------------

PATHOLOGY_REPORT_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    # Matches `sample.pathology_report_uuid` in SAMPLE_FIELDS.
    pa.field("pathology_report_uuid", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("file_name", pa.string()),
    pa.field("file_size", pa.int64()),
    pa.field("md5sum", pa.string()),
    # The PDF exactly as GDC serves it. Stored as parquet BYTE_ARRAY rather
    # than a base64 string: on this corpus binary+snappy lands at 0.92x the
    # raw bytes where base64+snappy is 1.26x, and `datasets` surfaces it as
    # Value("binary") either way.
    pa.field("pdf_bytes", pa.binary()),
]

# ---------------------------------------------------------------------------
# Derived: ssGSEA pathway activity, one record per scored RNA-Seq aliquot
#
# Struct-of-arrays, mirroring EXPRESSION_FIELDS: the consolidated layout
# already stores per-aliquot vectors that way, and it keeps a patient row to
# one record per aliquot per collection rather than one per (aliquot,
# pathway). `pathway` and the value arrays are index-aligned.
#
# The tabular layout's flat `ssgsea_scores_<collection>` table is the same
# numbers unpivoted; see that schema for why only the raw score is stored.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Copy number / miRNA / protein, consolidated-row shape
#
# Struct-of-arrays, matching EXPRESSION_FIELDS: one record per source file,
# with the per-measurement columns as index-aligned arrays inside it. That
# keeps a patient row at one struct per assay run rather than thousands of
# tiny structs, and lets a consumer column-project a single measurement
# vector without materializing the rest.
#
# These carry fewer FK columns than their tabular counterparts on purpose.
# The consolidated row already holds the full `samples` tree, so submitter
# ids and sample types are one lookup away; the tabular tables have no such
# neighbour and must denormalize.
# ---------------------------------------------------------------------------

# ASCAT is a paired caller and all three of its workflows ship for
# overlapping aliquots, so a case can carry several records for the same
# tumour aliquot. `workflow_type` is scalar here — one record per (aliquot,
# workflow) — which makes "give me the ASCAT3 calls" a filter on the struct
# rather than a filter inside the arrays.
ALLELE_SPECIFIC_CNV_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_id", pa.string()),
    # "ASCAT2" | "ASCAT3" | "AscatNGS".
    pa.field("workflow_type", pa.string()),
    # "Genotyping Array" for ASCAT2 / ASCAT3, "WGS" for AscatNGS.
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # `chr`-prefixed ("chr1"), unlike the masked segments below.
    pa.field("chromosome", pa.list_(pa.string())),
    pa.field("start", pa.list_(pa.int64())),
    pa.field("end", pa.list_(pa.int64())),
    pa.field("copy_number", pa.list_(pa.int32())),
    pa.field("major_copy_number", pa.list_(pa.int32())),
    pa.field("minor_copy_number", pa.list_(pa.int32())),
]

# DNAcopy log2 ratios against a diploid reference, germline CNVs masked.
# Relative, not absolute — see the dataset card for why this and the
# allele-specific calls are not interchangeable.
MASKED_CNV_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("workflow_type", pa.string()),
    pa.field("source_file_id", pa.string()),
    # Bare chromosome names ("1"), unlike the allele-specific segments.
    pa.field("chromosome", pa.list_(pa.string())),
    pa.field("start", pa.list_(pa.int64())),
    pa.field("end", pa.list_(pa.int64())),
    pa.field("num_probes", pa.list_(pa.int32())),
    pa.field("segment_mean", pa.list_(pa.float64())),
]

MIRNA_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("mirna_id", pa.list_(pa.string())),
    pa.field("read_count", pa.list_(pa.int64())),
    pa.field("reads_per_million_mirna_mapped", pa.list_(pa.float64())),
    # "Y" where reads also aligned elsewhere, so the count is not uniquely
    # attributable. Source header is `cross-mapped`.
    pa.field("cross_mapped", pa.list_(pa.string())),
]

# RPPA attaches to a portion rather than an aliquot — the only modality in
# this dataset that does — so it carries `portion_id` where its siblings
# carry `aliquot_id`.
PROTEIN_EXPRESSION_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("portion_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("agid", pa.list_(pa.string())),
    pa.field("lab_id", pa.list_(pa.string())),
    pa.field("catalog_number", pa.list_(pa.string())),
    # Antibody panel version; the panel grew over the project's life.
    pa.field("set_id", pa.list_(pa.string())),
    pa.field("peptide_target", pa.list_(pa.string())),
    # Null entries are the source's literal `NA` — a failed measurement,
    # not a zero.
    pa.field("protein_expression", pa.list_(pa.float64())),
]


SSGSEA_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("pathway", pa.list_(pa.string())),
    pa.field("pathway_url", pa.list_(pa.string())),
    pa.field("matched_gene_count", pa.list_(pa.int32())),
    pa.field("original_gene_count", pa.list_(pa.int32())),
    pa.field("score_raw", pa.list_(pa.float64())),
]


def ssgsea_patient_column(collection: str) -> str:
    return f"samples_ssgsea_{collection}"


# WikiPathways is deliberately absent: its weak sets are miRNA-centric and
# this assay cannot measure miRNAs. See `tcga2hf_pipeline.msigdb`.
SSGSEA_COLLECTIONS: list[str] = [
    "hallmark",
    "reactome",
    "pid",
    "oncogenic",
    "cancer_cell_atlas",
]


# ---------------------------------------------------------------------------
# Top-level patient row
# ---------------------------------------------------------------------------

PATIENT_FIELDS: list[pa.Field] = [
    pa.field("case_id", pa.string()),
    pa.field("case_submitter_id", pa.string()),
    pa.field("project_id", pa.string()),
    # Convenience link to this case's GDC Data Portal page. Templated from
    # case_id at row-build time so the HF dataset viewer renders it as a
    # clickable URL and pandas / polars users get it for free.
    pa.field("gdc_portal_url", pa.string()),
    pa.field("primary_site", pa.string()),
    pa.field("disease_type", pa.string()),
    # GDC `case` entity timeline anchors. index_date names the kind of event
    # used as the day-zero reference (TCGA: nearly always "Diagnosis").
    # All days_to_* fields throughout this row use this anchor.
    pa.field("index_date", pa.string()),
    pa.field("consent_type", pa.string()),
    pa.field("days_to_consent", pa.int64()),
    pa.field("days_to_lost_to_followup", pa.int64()),
    pa.field("lost_to_followup", pa.string()),
    pa.field("demographic", pa.struct(DEMOGRAPHIC_FIELDS)),
    pa.field("diagnoses", pa.list_(pa.struct(DIAGNOSIS_FIELDS))),
    pa.field("follow_ups", pa.list_(pa.struct(FOLLOW_UP_FIELDS))),
    pa.field("exposures", pa.list_(pa.struct(EXPOSURE_FIELDS))),
    pa.field("family_histories", pa.list_(pa.struct(FAMILY_HISTORY_FIELDS))),
    pa.field("samples", pa.list_(pa.struct(SAMPLE_FIELDS))),
    # GDC data_type-named molecular columns. Each is a list of records keyed
    # back to a sample/aliquot via FKs in the struct, so users can fetch
    # only the modalities they want via top-level Parquet column projection.
    pa.field("samples_masked_somatic_mutation", pa.list_(pa.struct(MUTATION_FIELDS))),
    pa.field(
        "samples_gene_expression_quantification",
        pa.list_(pa.struct(EXPRESSION_FIELDS)),
    ),
    pa.field("samples_pathology_report", pa.list_(pa.struct(PATHOLOGY_REPORT_FIELDS))),
    pa.field(
        "samples_allele_specific_copy_number_segment",
        pa.list_(pa.struct(ALLELE_SPECIFIC_CNV_FIELDS)),
    ),
    pa.field(
        "samples_masked_copy_number_segment",
        pa.list_(pa.struct(MASKED_CNV_FIELDS)),
    ),
    pa.field(
        "samples_mirna_expression_quantification",
        pa.list_(pa.struct(MIRNA_FIELDS)),
    ),
    pa.field(
        "samples_protein_expression_quantification",
        pa.list_(pa.struct(PROTEIN_EXPRESSION_FIELDS)),
    ),
    # One column per MSigDB collection, so a consumer can project just the
    # collection they need. Generated below from SSGSEA_COLLECTIONS, which
    # is defined after this list.
    # Survival endpoints — re-derived from the current GDC data using the
    # algorithm published by Liu et al. 2018 (Cell, TCGA Pan-Cancer Clinical
    # Data Resource). Implementation in `tcga2hf_pipeline.survival`;
    # validation against Liu's curated 2018 CDR workbook lives in
    # `dev_research/liu_2018/report.html`.
    #
    # Why we don't ship Liu's curated 2018 values directly: the CDR is a
    # frozen 2018 snapshot derived from a since-modified GDC release. Baking
    # those values into this dataset would lock in irreproducible source
    # drift. Re-deriving on every build keeps these values reproducible
    # from the dataset's other tables alone. Headline agreement against
    # Liu's CDR (both NA OR populated within 30 days): OS 98.2%, DSS 93.2%,
    # PFI 96.3%, DFI 90.1%.
    #
    # Sub-field semantics: `*_event` is 0/1 (event observed vs censored),
    # `*_time` is days from `index_date` (TCGA: diagnosis date). DFI is
    # null for SKCM / THYM / UVM / LAML — Liu specifies no DFI for those
    # tumor types.
    pa.field("survival_derived", pa.struct([
        pa.field("os_event", pa.int64()),
        pa.field("os_time", pa.float64()),
        pa.field("dss_event", pa.int64()),
        pa.field("dss_time", pa.float64()),
        pa.field("pfi_event", pa.int64()),
        pa.field("pfi_time", pa.float64()),
        pa.field("dfi_event", pa.int64()),
        pa.field("dfi_time", pa.float64()),
    ])),
]

# ssGSEA columns are appended after SSGSEA_COLLECTIONS is declared (below),
# so PATIENT_FIELDS stays the single ordered source of truth for the row.
def _append_ssgsea_patient_fields() -> None:
    for _collection in SSGSEA_COLLECTIONS:
        PATIENT_FIELDS.append(
            pa.field(ssgsea_patient_column(_collection), pa.list_(pa.struct(SSGSEA_FIELDS)))
        )


# Sub-fields of the `survival_derived` struct. Single source of truth for
# the new tabular `survival_derived` table (FK + one row per patient) and
# for `survival.attach_survival` to enumerate when populating both layouts.
SURVIVAL_DERIVED_FIELDS: list[pa.Field] = [
    f for f in next(f.type for f in PATIENT_FIELDS if f.name == "survival_derived")
]


# ---------------------------------------------------------------------------
# Tabular-dataset schemas (one row per GDC entity, one row per source-TSV row)
#
# Companion to the consolidated PATIENT_FIELDS layout. Same source data,
# decomposed into per-entity flat tables. FK columns (`case_id` etc.) are
# prepended to every child table so a user can join with a single key; we
# also pair every UUID FK with its `*_submitter_id` so HF Data Studio rows
# show human-readable values without needing extra joins.
#
# Built by `tcga2hf-pipeline build-tabular` and published to a separate
# HF dataset (`gabrielaltay/tcga-tabular-open`).
# ---------------------------------------------------------------------------


# Reusable FK blocks for the flat molecular tables.
_CASE_FKS: list[pa.Field] = [
    pa.field("case_id", pa.string()),
    pa.field("case_submitter_id", pa.string()),
]
_ALIQUOT_FKS: list[pa.Field] = [
    pa.field("aliquot_id", pa.string()),
    pa.field("aliquot_submitter_id", pa.string()),
]


# Cases: one row per patient with the GDC `cases.json` structure preserved.
# Mirrors PATIENT_FIELDS minus every molecular column (each of those has
# its own flat table below). Each top-level JSON key in the GDC `/cases`
# response maps to one column here — scalars stay scalar, struct fields
# stay struct, list-of-struct fields stay list-of-struct. The table name
# `cases` matches the source file name (`cases.json`).
#
# Derived by exclusion rather than by listing what to keep, so a new
# clinical field added to PATIENT_FIELDS reaches the `cases` table
# automatically. The cost is that a new *molecular* column must be named
# here too, or it would leak into `cases` and duplicate its own table —
# `test_cases_table_excludes_every_molecular_column` guards that.
_MOLECULAR_PATIENT_COLUMNS: set[str] = {
    "samples_masked_somatic_mutation",
    "samples_gene_expression_quantification",
    "samples_pathology_report",
    "samples_allele_specific_copy_number_segment",
    "samples_masked_copy_number_segment",
    "samples_mirna_expression_quantification",
    "samples_protein_expression_quantification",
    *(ssgsea_patient_column(c) for c in SSGSEA_COLLECTIONS),
}

TABULAR_CASES_FIELDS: list[pa.Field] = [
    f for f in PATIENT_FIELDS if f.name not in _MOLECULAR_PATIENT_COLUMNS
]

# Mutations: MUTATION_FIELDS already carries `case_id` (column 132 of the
# MAF), `tumor_sample_id`, `matched_normal_sample_id`, `source_file_id`. We
# prepend `case_submitter_id` for browseability and otherwise ship the MAF
# verbatim — same shape as the consolidated dataset's nested struct, just
# emitted as one row per variant.
TABULAR_MUTATIONS_FIELDS: list[pa.Field] = [
    pa.field("case_submitter_id", pa.string()),
    *MUTATION_FIELDS,
]

# Expression: one row per source-TSV row (4 N_* QC rows + ~60660 gene rows
# per aliquot), with all original TSV columns preserved verbatim. Notably
# keeps `stranded_first` / `stranded_second` (the consolidated dataset
# drops them per GDC's harmonization choice; the tabular dataset is closer
# to the source and includes them).
TABULAR_EXPRESSION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("gene_id", pa.string()),
    pa.field("gene_name", pa.string()),
    pa.field("gene_type", pa.string()),
    pa.field("unstranded", pa.int64()),
    pa.field("stranded_first", pa.int64()),
    pa.field("stranded_second", pa.int64()),
    pa.field("tpm_unstranded", pa.float64()),
    pa.field("fpkm_unstranded", pa.float64()),
    pa.field("fpkm_uq_unstranded", pa.float64()),
]

# Files: provenance table from each project's modality manifest.json.
# One row per (file_id, case_id) — most files are 1:1 with cases for these
# modalities, but a file can in principle reference multiple cases.
TABULAR_FILES_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    pa.field("file_id", pa.string()),
    pa.field("file_name", pa.string()),
    pa.field("file_size", pa.int64()),
    pa.field("md5sum", pa.string()),
    pa.field("data_category", pa.string()),
    pa.field("data_type", pa.string()),
    pa.field("data_format", pa.string()),
    pa.field("experimental_strategy", pa.string()),
    pa.field("workflow_type", pa.string()),
    pa.field("access", pa.string()),
    # Per-file version provenance from GDC's /files/versions. `gdc_version`
    # is the file's own version and `gdc_first_release` the GDC release it
    # first appeared in — together they identify the bytes independently of
    # which release we happened to fetch at (the API only serves the
    # current one). `gdc_superseded` is true when GDC has since replaced
    # this file with a newer version under a different id.
    pa.field("gdc_version", pa.string()),
    pa.field("gdc_first_release", pa.string()),
    pa.field("gdc_superseded", pa.bool_()),
    # Local label naming the project subdir the file came from
    # (`mutations` / `expression` / ...).
    pa.field("modality", pa.string()),
]


# Survival endpoints (one row per patient) — flat view of the
# `survival_derived` struct from PATIENT_FIELDS. Same eight values; this
# layout suits the tabular dataset's SQL-friendly purpose so users can
# `SELECT case_submitter_id, os_event, os_time FROM survival_derived`
# without unnesting. Provenance / methodology lives in the `survival_derived`
# field comment in PATIENT_FIELDS above.
TABULAR_SURVIVAL_DERIVED_FIELDS: list[pa.Field] = [
    pa.field("case_submitter_id", pa.string()),
    *SURVIVAL_DERIVED_FIELDS,
]


# Pathology reports: one row per report PDF. Reports are near-1:1 with cases
# pan-TCGA (11,208 reports / 11,121 cases), so this table stays small in row
# count and large only in bytes.
TABULAR_PATHOLOGY_REPORT_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *PATHOLOGY_REPORT_FIELDS,
]


# Sample-level FKs carried on the per-aliquot molecular tables. `sample_type`
# is denormalized alongside the ids for the same reason it is on the ssGSEA
# scores table: tumor-vs-normal is the dominant filter on every molecular
# measurement, and recovering it otherwise means unnesting `cases.samples`.
_SAMPLE_FKS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    pa.field("sample_type", pa.string()),
]


# Copy number, segment level — the two data types GDC serves for TCGA.
#
# Column names are lowercased from the source headers (`Copy_Number` ->
# `copy_number`, `Num_Probes` -> `num_probes`). The seg files are not a
# published spec the way MAF is, their own capitalisation is inconsistent
# between the two types, and lowercase keeps the columns usable as bare SQL
# identifiers. Values are untouched.
#
# Deliberately absent: `Gene Level Copy Number`. GDC serves it as the same
# calls projected onto GENCODE v36, at 34 GB per workflow, and the
# projection is exactly reproducible from `allele_specific_copy_number_segment`
# — so it is a derivation to add later, not source data we are missing.

# ASCAT is a paired caller, so each file names two aliquots. The tumour one
# is identified positively — it is the aliquot the file's own `GDC_Aliquot`
# column reports — rather than by reading sample-type digits out of a
# barcode. The other associated aliquot is the matched normal.
#
# `workflow_type` is a first-class column here, not provenance trivia.
# ASCAT2, ASCAT3 and AscatNGS all ship for overlapping aliquots, and each
# fits purity and ploidy independently, so they can disagree — on TCGA-CHOL
# ASCAT2 and ASCAT3 give the same length-weighted modal copy number for
# 33 of 36 shared aliquots, and where they differ they differ substantially
# (one aliquot is modal 2 under ASCAT2 and modal 4 under ASCAT3). ASCAT3
# also segments more coarsely: 2,469 segments against ASCAT2's 6,580 over
# the same aliquots. A query that does not filter on `workflow_type` is
# pooling three different answers to the same question.
TABULAR_ALLELE_SPECIFIC_CNV_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("matched_normal_aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_submitter_id", pa.string()),
    # "ASCAT2" | "ASCAT3" | "AscatNGS".
    pa.field("workflow_type", pa.string()),
    # "Genotyping Array" for ASCAT2 / ASCAT3, "WGS" for AscatNGS.
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # `chr`-prefixed in this data type ("chr1"), bare in the masked segments
    # ("1"). Carried as each file writes it; see the dataset card.
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
    # Total integer copy number, and its split into the major and minor
    # allele. minor == 0 with major > 0 is loss of heterozygosity.
    pa.field("copy_number", pa.int32()),
    pa.field("major_copy_number", pa.int32()),
    pa.field("minor_copy_number", pa.int32()),
]

# DNAcopy circular-binary-segmentation output with germline CNVs masked out.
# Unlike the allele-specific type this is a *relative* measurement:
# `segment_mean` is log2(sample / reference), so 0 is copy-neutral and there
# is no integer call and no allelic split.
#
# The two types agree in direction but are not interchangeable, and the gap
# is informative rather than noise. Nesting each masked segment inside its
# containing ASCAT3 segment on TCGA-CHOL (2,590 pairs) gives Spearman +0.56,
# with median `segment_mean` rising monotonically across integer copy number
# (CN 0 -> -1.93, CN 1 -> -0.44, CN 2 -> +0.07, CN 4 -> +0.22, CN 8 -> +1.25).
# The correlation is only moderate because ASCAT corrects for tumour purity
# and ploidy while DNAcopy's ratio is against a diploid reference: in a
# hyperdiploid tumour, integer CN 3 is copy-neutral relative to its own
# baseline but still reads near log2 0 here. Use the allele-specific calls
# for absolute copy number, the masked segments for reference-relative ratio.
TABULAR_MASKED_CNV_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("workflow_type", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
    # Array probes supporting the segment — the segment's evidence weight.
    pa.field("num_probes", pa.int32()),
    pa.field("segment_mean", pa.float64()),
]


# miRNA-Seq, one row per (aliquot, miRBase v21 mature miRNA). ~1,881 miRNAs
# per aliquot.
TABULAR_MIRNA_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("mirna_id", pa.string()),
    pa.field("read_count", pa.int64()),
    pa.field("reads_per_million_mirna_mapped", pa.float64()),
    # "Y" when reads for this miRNA also aligned elsewhere in the genome, so
    # its count is not uniquely attributable. GDC ships the flag rather than
    # dropping the row; we do the same.
    pa.field("cross_mapped", pa.string()),
]


# Reverse Phase Protein Array. Unique among our molecular modalities in
# attaching to a *portion* rather than an aliquot, so it carries portion FKs
# and resolves the sample through the portion.
#
# Coverage is the narrowest we ship — 7,827 of 11,428 TCGA cases — because
# RPPA was only run on a subset, and the antibody panel itself grew over the
# project's life (`set_id` distinguishes the panel versions). A peptide
# target absent for a sample may mean "not measured on that panel" rather
# than "measured as zero".
TABULAR_PROTEIN_EXPRESSION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    pa.field("portion_id", pa.string()),
    pa.field("portion_submitter_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    # MD Anderson's antibody id, stable across panel versions.
    pa.field("agid", pa.string()),
    pa.field("lab_id", pa.string()),
    pa.field("catalog_number", pa.string()),
    # Antibody panel version this measurement came from ("Old", "V1.2", ...).
    pa.field("set_id", pa.string()),
    # The protein or phospho-site, e.g. "AKT_pS473".
    pa.field("peptide_target", pa.string()),
    # Replicate-based normalized log2 signal; centred near 0, sign-meaningful.
    pa.field("protein_expression", pa.float64()),
]


# ssGSEA pathway activity. Two tables per gene-set collection, named
# `ssgsea_scores_<collection>` and `ssgsea_stats_<collection>` — grouping by
# kind rather than by collection so every scores table sorts together in the
# HF config list, and adding a collection is two new tables rather than new
# columns on an existing one (which would rewrite every row).
#
# `score_raw` is deliberately the only score column. GSVA's `normalize=TRUE`
# divides by the range of the entire score matrix, which makes a score depend
# on the cohort and the collection it was computed alongside rather than on
# the sample. Raw scores depend on nothing but their own sample, so they can
# be computed per project, stay valid when projects or collections are added
# later, and still yield the normalized view on demand — the divisor is
# recoverable from the stats table as MAX(max) - MIN(min) over its
# `pan_cancer` rows.

TABULAR_SSGSEA_SCORES_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    # Carried despite the expression table not carrying it: tumor-vs-normal
    # is the dominant filter on pathway activity, and recovering it
    # otherwise means unnesting `cases.samples`.
    pa.field("sample_type", pa.string()),
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("pathway", pa.string()),
    # Link to the authoritative MSigDB definition of this gene set, so a
    # consumer can check what a score actually means without leaving the
    # table. Templated from the pathway name (same pattern as
    # `gdc_portal_url`); verified derivable for all 26,937 pathways across
    # the collections we ship.
    pa.field("pathway_url", pa.string()),
    # Per-pathway provenance. Constant within a pathway, so dictionary
    # encoding makes it ~1% of the table, and it lets a consumer filter on
    # gene-set coverage without a join.
    pa.field("matched_gene_count", pa.int32()),
    pa.field("original_gene_count", pa.int32()),
    pa.field("score_raw", pa.float64()),
]

# Reference distributions for turning raw scores into z-scores or GSVA-style
# normalized values. Every value here is derivable from the scores tables by
# aggregation — this is a materialized convenience view, not new evidence.
# Each project ships its own rows *plus* the pan-cancer rows, so a consumer
# who loads one project can still normalize against all of TCGA without
# scanning 33 configs.
TABULAR_SSGSEA_STATS_FIELDS: list[pa.Field] = [
    # "pan_cancer" (every project) or "project" (this project alone).
    pa.field("population", pa.string()),
    # Null on pan_cancer rows.
    pa.field("project_id", pa.string()),
    # Null means every sample type; otherwise the type the row is restricted to.
    pa.field("sample_type", pa.string()),
    pa.field("pathway", pa.string()),
    pa.field("n_aliquots", pa.int64()),
    pa.field("mean", pa.float64()),
    # Sample standard deviation (ddof=1); null when n_aliquots < 2.
    pa.field("sd", pa.float64()),
    pa.field("min", pa.float64()),
    pa.field("q25", pa.float64()),
    pa.field("median", pa.float64()),
    pa.field("q75", pa.float64()),
    pa.field("max", pa.float64()),
]


_append_ssgsea_patient_fields()
PATIENTS = pa.schema(PATIENT_FIELDS)


def ssgsea_scores_table(collection: str) -> str:
    return f"ssgsea_scores_{collection}"


def ssgsea_stats_table(collection: str) -> str:
    return f"ssgsea_stats_{collection}"


# Map of table-name → schema, used by the build-tabular command and the
# dataset card generator. Table names mirror the GDC's stable concepts:
# `cases` (cases.json), `masked_somatic_mutation` and
# `gene_expression_quantification` (snake_cased GDC `data_type` enum
# values), `files` (per-modality manifests, derived from the GDC `/files`
# endpoint). The exception is `survival_derived` — a value-added table
# of re-derived OS / DSS / PFI / DFI endpoints (Liu et al. 2018 algorithm)
# that doesn't correspond to a single GDC concept; provenance is in the
# dataset card's "Survival endpoints" section.
TABULAR_TABLES: dict[str, pa.Schema] = {
    "cases": pa.schema(TABULAR_CASES_FIELDS),
    "masked_somatic_mutation": pa.schema(TABULAR_MUTATIONS_FIELDS),
    "gene_expression_quantification": pa.schema(TABULAR_EXPRESSION_FIELDS),
    "files": pa.schema(TABULAR_FILES_FIELDS),
    "survival_derived": pa.schema(TABULAR_SURVIVAL_DERIVED_FIELDS),
    "pathology_report": pa.schema(TABULAR_PATHOLOGY_REPORT_FIELDS),
    "allele_specific_copy_number_segment": pa.schema(TABULAR_ALLELE_SPECIFIC_CNV_FIELDS),
    "masked_copy_number_segment": pa.schema(TABULAR_MASKED_CNV_FIELDS),
    "mirna_expression_quantification": pa.schema(TABULAR_MIRNA_FIELDS),
    "protein_expression_quantification": pa.schema(TABULAR_PROTEIN_EXPRESSION_FIELDS),
    # One scores + one stats table per gene-set collection. Extending to
    # Reactome or WikiPathways is an entry in SSGSEA_COLLECTIONS; the
    # schemas, emitters and tests are all collection-agnostic.
    **{ssgsea_scores_table(c): pa.schema(TABULAR_SSGSEA_SCORES_FIELDS) for c in SSGSEA_COLLECTIONS},
    **{ssgsea_stats_table(c): pa.schema(TABULAR_SSGSEA_STATS_FIELDS) for c in SSGSEA_COLLECTIONS},
}
