"""Patient-row pyarrow schema, derived from the GDC Data Dictionary.

## Provenance

These field lists are exhaustive snapshots from the gdcdictionary YAML files
(https://github.com/NCI-GDC/gdcdictionary), with a few system properties
(state / created_datetime / updated_datetime / project_id / relationship
pointers) excluded. We bake them in statically so the parquet schema is
deterministic at build time rather than subject to live-API drift.

Two related artifacts:

  - **This file** is the build-time schema we write parquet against. The
    clinical entity sections were generated by
    `scripts/regenerate_clinical_fields.py /path/to/gdcdictionary` and
    pasted in. Re-run when the dictionary changes upstream.
  - **Per-fetch dictionary snapshot** at
    `<data-dir>/raw/gdc_dictionary.<major>.<minor>.json` is the live
    dictionary the GDC was serving when the data was fetched. Its SHA-256 is
    recorded in each project's `gdc_status.json`. This is the authoritative
    "what was the dictionary when this data shipped" record; if it diverges
    from the static schema in this file, regenerate.

Type assignments come from each property's `type` (or `oneOf`) declaration;
enums map to `pa.string()`. The MAF-derived `MUTATION_FIELDS` and TSV-derived
`EXPRESSION_FIELDS` follow the same all-fields-preserved principle for their
respective formats.
"""

from __future__ import annotations

import pyarrow as pa

# ---------------------------------------------------------------------------
# Clinical entities (case → demographic / diagnoses / follow_ups / etc.)
# Field lists generated from gdcdictionary YAML; ordered by dependency so
# parents reference their children's *_FIELDS by name.
# ---------------------------------------------------------------------------

DEMOGRAPHIC_FIELDS: list[pa.Field] = [
    pa.field("demographic_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("age_at_index", pa.int64()),
    pa.field("age_is_obfuscated", pa.bool_()),
    pa.field("cause_of_death", pa.string()),
    pa.field("cause_of_death_source", pa.string()),
    pa.field("country_of_birth", pa.string()),
    pa.field("country_of_residence_at_enrollment", pa.string()),
    pa.field("days_to_birth", pa.int64()),
    pa.field("days_to_death", pa.int64()),
    pa.field("education_level", pa.string()),
    pa.field("ethnicity", pa.string()),
    pa.field("marital_status", pa.string()),
    pa.field("occupation_duration_years", pa.int64()),
    pa.field("population_group", pa.string()),
    pa.field("race", pa.string()),
    pa.field("sex_at_birth", pa.string()),
    pa.field("vital_status", pa.string()),
    pa.field("year_of_birth", pa.int64()),
    pa.field("year_of_birth_range", pa.string()),
    pa.field("year_of_death", pa.int64()),
]

TREATMENT_FIELDS: list[pa.Field] = [
    pa.field("treatment_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("chemo_concurrent_to_radiation", pa.string()),
    pa.field("clinical_trial_indicator", pa.string()),
    pa.field("course_number", pa.float64()),
    pa.field("days_to_treatment_end", pa.int64()),
    pa.field("days_to_treatment_start", pa.int64()),
    pa.field("drug_category", pa.string()),
    pa.field("embolic_agent", pa.string()),
    pa.field("initial_disease_status", pa.string()),
    pa.field("lesions_treated_number", pa.float64()),
    pa.field("margin_distance", pa.float64()),
    pa.field("margin_status", pa.string()),
    pa.field("margins_involved_site", pa.string()),
    pa.field("number_of_cycles", pa.int64()),
    pa.field("number_of_fractions", pa.float64()),
    pa.field("prescribed_dose", pa.float64()),
    pa.field("prescribed_dose_units", pa.string()),
    pa.field("pretreatment", pa.string()),
    pa.field("protocol_identifier", pa.string()),
    pa.field("radiosensitizing_agent", pa.string()),
    pa.field("reason_treatment_ended", pa.string()),
    pa.field("reason_treatment_not_given", pa.string()),
    pa.field("regimen_or_line_of_therapy", pa.string()),
    pa.field("residual_disease", pa.string()),
    pa.field("route_of_administration", pa.list_(pa.string())),
    pa.field("therapeutic_agents", pa.string()),
    pa.field("therapeutic_levels_achieved", pa.string()),
    pa.field("therapeutic_target_level", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("treatment_anatomic_sites", pa.list_(pa.string())),
    pa.field("treatment_dose", pa.int64()),
    pa.field("treatment_dose_max", pa.float64()),
    pa.field("treatment_dose_units", pa.string()),
    pa.field("treatment_duration", pa.int64()),
    pa.field("treatment_effect", pa.string()),
    pa.field("treatment_effect_indicator", pa.string()),
    pa.field("treatment_frequency", pa.string()),
    pa.field("treatment_intent_type", pa.string()),
    pa.field("treatment_or_therapy", pa.string()),
    pa.field("treatment_outcome", pa.string()),
    pa.field("treatment_outcome_duration", pa.int64()),
    pa.field("treatment_type", pa.string()),
    pa.field("treatment_type_administered", pa.string()),
]

# ---------------------------------------------------------------------------
# GDC `/cases` entities added to reach full expansion coverage.
#
# The `cases` table is the flattening of one GDC `/cases` response per
# patient, and that endpoint's shape is set by its `expand` parameter. We
# previously asked for 11 of the 41 expandable groups; these constants cover
# the rest of the non-`files` ones. The `files.*` subtree is deliberately
# still excluded: it is 190 KB per case against 16 KB for everything here
# (~2.2 GB pan-TCGA), and it duplicates the richer `files` table we build
# from the `/files` endpoint's own manifests.
#
# Fields are taken verbatim from `GET /cases/_mapping`, minus the
# record-keeping columns (`created_datetime`, `updated_datetime`, `state`,
# and the `legacy_*` pair on annotations) that every other entity in this
# schema already drops.
# ---------------------------------------------------------------------------

ANNOTATION_FIELDS: list[pa.Field] = [
    pa.field("annotation_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("case_id", pa.string()),
    pa.field("case_submitter_id", pa.string()),
    pa.field("category", pa.string()),
    pa.field("classification", pa.string()),
    pa.field("creator", pa.string()),
    pa.field("entity_id", pa.string()),
    pa.field("entity_submitter_id", pa.string()),
    pa.field("entity_type", pa.string()),
    pa.field("notes", pa.string()),
    pa.field("status", pa.string()),
]


PATHOLOGY_DETAIL_FIELDS: list[pa.Field] = [
    pa.field("pathology_detail_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("additional_pathology_findings", pa.string()),
    pa.field("anaplasia_present", pa.string()),
    pa.field("anaplasia_present_type", pa.string()),
    pa.field("bone_marrow_malignant_cells", pa.string()),
    pa.field("breslow_thickness", pa.float64()),
    pa.field("breslow_thickness_category", pa.string()),
    pa.field("circumferential_resection_margin", pa.float64()),
    pa.field("columnar_mucosa_present", pa.string()),
    pa.field("consistent_pathology_review", pa.string()),
    pa.field("days_to_pathology_detail", pa.int64()),
    pa.field("dysplasia_degree", pa.string()),
    pa.field("dysplasia_type", pa.string()),
    pa.field("epithelioid_cell_percent_range", pa.string()),
    pa.field("extracapsular_extension", pa.string()),
    pa.field("extracapsular_extension_present", pa.string()),
    pa.field("extranodal_extension", pa.string()),
    pa.field("extraocular_nodule_size", pa.string()),
    pa.field("extrascleral_extension_present", pa.string()),
    pa.field("extrathyroid_extension", pa.string()),
    pa.field("greatest_tumor_dimension", pa.float64()),
    pa.field("gross_tumor_weight", pa.float64()),
    pa.field("histologic_progression_type", pa.string()),
    pa.field("intratubular_germ_cell_neoplasia_present", pa.string()),
    pa.field("largest_extrapelvic_peritoneal_focus", pa.string()),
    pa.field("lymph_node_dissection_method", pa.string()),
    pa.field("lymph_node_dissection_site", pa.string()),
    pa.field("lymph_node_involved_site", pa.string()),
    pa.field("lymph_node_involvement", pa.string()),
    pa.field("lymph_nodes_positive", pa.int64()),
    pa.field("lymph_nodes_removed", pa.string()),
    pa.field("lymph_nodes_tested", pa.int64()),
    pa.field("lymphatic_invasion_present", pa.string()),
    pa.field("margin_status", pa.string()),
    pa.field("measurement_type", pa.string()),
    pa.field("measurement_unit", pa.string()),
    pa.field("metaplasia_present", pa.string()),
    pa.field("micrometastasis_present", pa.string()),
    pa.field("morphologic_architectural_pattern", pa.string()),
    pa.field("necrosis_percent", pa.float64()),
    pa.field("necrosis_present", pa.string()),
    pa.field("non_nodal_regional_disease", pa.string()),
    pa.field("non_nodal_tumor_deposits", pa.string()),
    pa.field("number_proliferating_cells", pa.int64()),
    pa.field("percent_tumor_invasion", pa.float64()),
    pa.field("percent_tumor_nuclei", pa.float64()),
    pa.field("perineural_invasion_present", pa.string()),
    pa.field("peripancreatic_lymph_nodes_positive", pa.string()),
    pa.field("peripancreatic_lymph_nodes_tested", pa.int64()),
    pa.field("prcc_type", pa.string()),
    pa.field("prostatic_chips_positive_count", pa.float64()),
    pa.field("prostatic_chips_total_count", pa.float64()),
    pa.field("prostatic_involvement_percent", pa.float64()),
    pa.field("residual_tumor", pa.string()),
    pa.field("residual_tumor_measurement", pa.string()),
    pa.field("rhabdoid_percent", pa.float64()),
    pa.field("rhabdoid_present", pa.string()),
    pa.field("sarcomatoid_percent", pa.float64()),
    pa.field("sarcomatoid_present", pa.string()),
    pa.field("spindle_cell_percent_range", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("transglottic_extension", pa.string()),
    pa.field("tumor_basal_diameter", pa.float64()),
    pa.field("tumor_burden", pa.float64()),
    pa.field("tumor_depth_descriptor", pa.string()),
    pa.field("tumor_depth_measurement", pa.float64()),
    pa.field("tumor_infiltrating_lymphocytes", pa.string()),
    pa.field("tumor_infiltrating_macrophages", pa.string()),
    pa.field("tumor_largest_dimension_diameter", pa.float64()),
    pa.field("tumor_length_measurement", pa.float64()),
    # Multi-valued: GDC types it `keyword` but returns an array (356
    # records pan-TCGA).
    pa.field("tumor_level_prostate", pa.list_(pa.string())),
    pa.field("tumor_shape", pa.string()),
    pa.field("tumor_thickness", pa.float64()),
    pa.field("tumor_width_measurement", pa.float64()),
    pa.field("vascular_invasion_present", pa.string()),
    pa.field("vascular_invasion_type", pa.string()),
    pa.field("zone_of_origin_prostate", pa.string()),
]


MOLECULAR_TEST_FIELDS: list[pa.Field] = [
    pa.field("molecular_test_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("aa_change", pa.string()),
    pa.field("aneuploidy", pa.string()),
    pa.field("antigen", pa.string()),
    pa.field("biospecimen_type", pa.string()),
    pa.field("biospecimen_volume", pa.float64()),
    pa.field("blood_test_normal_range_lower", pa.float64()),
    pa.field("blood_test_normal_range_upper", pa.float64()),
    pa.field("cell_count", pa.int64()),
    pa.field("chromosomal_translocation", pa.string()),
    pa.field("chromosome", pa.string()),
    pa.field("chromosome_arm", pa.string()),
    pa.field("clonality", pa.string()),
    pa.field("copy_number", pa.float64()),
    pa.field("cytoband", pa.string()),
    pa.field("days_to_test", pa.int64()),
    pa.field("exon", pa.string()),
    pa.field("gene_symbol", pa.string()),
    pa.field("histone_family", pa.string()),
    pa.field("histone_variant", pa.string()),
    pa.field("hpv_strain", pa.string()),
    pa.field("intron", pa.string()),
    pa.field("laboratory_test", pa.string()),
    pa.field("loci_abnormal_count", pa.int64()),
    pa.field("loci_count", pa.int64()),
    pa.field("locus", pa.string()),
    pa.field("mismatch_repair_mutation", pa.string()),
    pa.field("mitotic_count", pa.float64()),
    pa.field("mitotic_total_area", pa.float64()),
    pa.field("molecular_analysis_method", pa.string()),
    pa.field("molecular_consequence", pa.string()),
    pa.field("mutation_codon", pa.string()),
    pa.field("pathogenicity", pa.string()),
    pa.field("ploidy", pa.string()),
    pa.field("second_exon", pa.string()),
    pa.field("second_gene_symbol", pa.string()),
    pa.field("specialized_molecular_test", pa.string()),
    pa.field("staining_intensity_scale", pa.string()),
    pa.field("staining_intensity_value", pa.string()),
    pa.field("test_analyte_type", pa.string()),
    pa.field("test_result", pa.string()),
    pa.field("test_units", pa.string()),
    pa.field("test_value", pa.float64()),
    pa.field("test_value_range", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("transcript", pa.string()),
    pa.field("variant_origin", pa.string()),
    pa.field("variant_type", pa.string()),
    pa.field("zygosity", pa.string()),
]


OTHER_CLINICAL_ATTRIBUTE_FIELDS: list[pa.Field] = [
    pa.field("other_clinical_attribute_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("aids_risk_factors", pa.string()),
    pa.field("bmi", pa.float64()),
    pa.field("body_surface_area", pa.float64()),
    pa.field("cd4_count", pa.float64()),
    pa.field("cdc_hiv_risk_factors", pa.string()),
    # Multi-valued despite the `keyword` mapping (626 records pan-TCGA).
    pa.field("comorbidities", pa.list_(pa.string())),
    pa.field("comorbidity_method_of_diagnosis", pa.string()),
    pa.field("days_to_comorbidity", pa.int64()),
    pa.field("days_to_risk_factor", pa.int64()),
    pa.field("diabetes_treatment_type", pa.string()),
    pa.field("dlco_ref_predictive_percent", pa.float64()),
    pa.field("exercise_frequency_weekly", pa.string()),
    pa.field("eye_color", pa.string()),
    pa.field("fertility_history", pa.string()),
    pa.field("fev1_fvc_post_bronch_percent", pa.float64()),
    pa.field("fev1_fvc_pre_bronch_percent", pa.float64()),
    pa.field("fev1_ref_post_bronch_percent", pa.float64()),
    pa.field("fev1_ref_pre_bronch_percent", pa.float64()),
    pa.field("haart_treatment_indicator", pa.string()),
    pa.field("height", pa.float64()),
    pa.field("hepatitis_sustained_virological_response", pa.string()),
    pa.field("hiv_viral_load", pa.float64()),
    pa.field("hormonal_contraceptive_type", pa.string()),
    pa.field("hormonal_contraceptive_use", pa.string()),
    pa.field("hormonal_replacement_therapy_status", pa.string()),
    pa.field("hormone_replacement_therapy_type", pa.string()),
    pa.field("hysterectomy_margins_involved", pa.string()),
    pa.field("hysterectomy_type", pa.string()),
    pa.field("immunosuppressive_treatment_type", pa.string()),
    pa.field("menopause_status", pa.string()),
    pa.field("myasthenia_gravis_classification", pa.string()),
    pa.field("nadir_cd4_count", pa.float64()),
    pa.field("nononcologic_therapeutic_agents", pa.string()),
    pa.field("number_of_pregnancies", pa.string()),
    pa.field("oxygen_use_indicator", pa.string()),
    pa.field("oxygen_use_type", pa.string()),
    pa.field("pancreatitis_onset_year", pa.int64()),
    pa.field("pregnancy_outcome", pa.string()),
    pa.field("pregnant_at_diagnosis", pa.string()),
    pa.field("premature_at_birth", pa.string()),
    pa.field("reflux_treatment_type", pa.string()),
    pa.field("risk_factor_method_of_diagnosis", pa.string()),
    pa.field("risk_factor_treatment", pa.string()),
    # Multi-valued despite the `keyword` mapping (2,015 records pan-TCGA).
    pa.field("risk_factors", pa.list_(pa.string())),
    pa.field("timepoint_category", pa.string()),
    pa.field("treatment_frequency", pa.string()),
    pa.field("undescended_testis_corrected", pa.string()),
    pa.field("undescended_testis_corrected_age_range", pa.string()),
    pa.field("undescended_testis_corrected_laterality", pa.string()),
    pa.field("undescended_testis_corrected_method", pa.string()),
    pa.field("undescended_testis_history", pa.string()),
    pa.field("undescended_testis_history_laterality", pa.string()),
    # Multi-valued despite the `keyword` mapping (296 records pan-TCGA).
    pa.field("viral_hepatitis_serology_tests", pa.list_(pa.string())),
    pa.field("weeks_gestation_at_birth", pa.float64()),
    pa.field("weight", pa.float64()),
]


PROGRAM_FIELDS: list[pa.Field] = [
    pa.field("program_id", pa.string()),
    pa.field("dbgap_accession_number", pa.string()),
    pa.field("name", pa.string()),
]


TISSUE_SOURCE_SITE_FIELDS: list[pa.Field] = [
    pa.field("tissue_source_site_id", pa.string()),
    pa.field("bcr_id", pa.string()),
    pa.field("code", pa.string()),
    pa.field("name", pa.string()),
    pa.field("project", pa.string()),
]


SLIDE_FIELDS: list[pa.Field] = [
    pa.field("slide_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("bone_marrow_malignant_cells", pa.string()),
    pa.field("number_proliferating_cells", pa.int64()),
    pa.field("percent_eosinophil_infiltration", pa.float64()),
    pa.field("percent_follicular_component", pa.float64()),
    pa.field("percent_granulocyte_infiltration", pa.float64()),
    pa.field("percent_inflam_infiltration", pa.float64()),
    pa.field("percent_lymphocyte_infiltration", pa.float64()),
    pa.field("percent_monocyte_infiltration", pa.float64()),
    pa.field("percent_necrosis", pa.float64()),
    pa.field("percent_neutrophil_infiltration", pa.float64()),
    pa.field("percent_normal_cells", pa.float64()),
    pa.field("percent_rhabdoid_features", pa.float64()),
    pa.field("percent_sarcomatoid_features", pa.float64()),
    pa.field("percent_stromal_cells", pa.float64()),
    pa.field("percent_tumor_cells", pa.float64()),
    pa.field("percent_tumor_nuclei", pa.float64()),
    pa.field("prostatic_chips_positive_count", pa.float64()),
    pa.field("prostatic_chips_total_count", pa.float64()),
    pa.field("prostatic_involvement_percent", pa.float64()),
    pa.field("section_location", pa.string()),
    pa.field("tissue_microarray_coordinates", pa.string()),
]


CENTER_FIELDS: list[pa.Field] = [
    pa.field("center_id", pa.string()),
    pa.field("center_type", pa.string()),
    pa.field("code", pa.string()),
    pa.field("name", pa.string()),
    pa.field("namespace", pa.string()),
    pa.field("short_name", pa.string()),
]


DIAGNOSIS_FIELDS: list[pa.Field] = [
    pa.field("diagnosis_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("adrenal_hormone", pa.string()),
    pa.field("age_at_diagnosis", pa.int64()),
    pa.field("ajcc_clinical_m", pa.string()),
    pa.field("ajcc_clinical_n", pa.string()),
    pa.field("ajcc_clinical_stage", pa.string()),
    pa.field("ajcc_clinical_t", pa.string()),
    pa.field("ajcc_pathologic_m", pa.string()),
    pa.field("ajcc_pathologic_n", pa.string()),
    pa.field("ajcc_pathologic_stage", pa.string()),
    pa.field("ajcc_pathologic_t", pa.string()),
    pa.field("ajcc_serum_tumor_markers", pa.string()),
    pa.field("ajcc_staging_system_edition", pa.string()),
    pa.field("ann_arbor_b_symptoms", pa.string()),
    pa.field("ann_arbor_b_symptoms_described", pa.string()),
    pa.field("ann_arbor_b_symptoms_described_array", pa.list_(pa.string())),
    pa.field("ann_arbor_clinical_stage", pa.string()),
    pa.field("ann_arbor_extranodal_involvement", pa.string()),
    pa.field("ann_arbor_pathologic_stage", pa.string()),
    pa.field("best_overall_response", pa.string()),
    pa.field("burkitt_lymphoma_clinical_variant", pa.string()),
    pa.field("calgb_risk_group", pa.string()),
    pa.field("cancer_detection_method", pa.string()),
    pa.field("child_pugh_classification", pa.string()),
    pa.field("clark_level", pa.string()),
    pa.field("classification_of_tumor", pa.string()),
    pa.field("cog_liver_stage", pa.string()),
    pa.field("cog_neuroblastoma_risk_group", pa.string()),
    pa.field("cog_renal_stage", pa.string()),
    pa.field("cog_rhabdomyosarcoma_risk_group", pa.string()),
    pa.field("contiguous_organ_invaded", pa.string()),
    pa.field("days_to_best_overall_response", pa.int64()),
    pa.field("days_to_diagnosis", pa.int64()),
    pa.field("days_to_last_follow_up", pa.float64()),
    pa.field("days_to_last_known_disease_status", pa.float64()),
    pa.field("days_to_recurrence", pa.float64()),
    pa.field("diagnosis_is_primary_disease", pa.bool_()),
    pa.field("double_expressor_lymphoma", pa.string()),
    pa.field("double_hit_lymphoma", pa.string()),
    pa.field("eln_risk_classification", pa.string()),
    pa.field("enneking_msts_grade", pa.string()),
    pa.field("enneking_msts_metastasis", pa.string()),
    pa.field("enneking_msts_stage", pa.string()),
    pa.field("enneking_msts_tumor_site", pa.string()),
    pa.field("ensat_clinical_m", pa.string()),
    pa.field("ensat_pathologic_n", pa.string()),
    pa.field("ensat_pathologic_stage", pa.string()),
    pa.field("ensat_pathologic_t", pa.string()),
    pa.field("esophageal_columnar_dysplasia_degree", pa.string()),
    pa.field("esophageal_columnar_metaplasia_present", pa.string()),
    pa.field("fab_morphology_code", pa.string()),
    pa.field("figo_stage", pa.string()),
    pa.field("figo_staging_edition_year", pa.string()),
    pa.field("first_symptom_longest_duration", pa.string()),
    pa.field("first_symptom_prior_to_diagnosis", pa.string()),
    pa.field("gastric_esophageal_junction_involvement", pa.string()),
    pa.field("gleason_grade_group", pa.string()),
    pa.field("gleason_grade_tertiary", pa.string()),
    pa.field("gleason_patterns_percent", pa.int64()),
    pa.field("gleason_score", pa.int64()),
    pa.field("goblet_cells_columnar_mucosa_present", pa.string()),
    pa.field("icd_10_code", pa.string()),
    pa.field("igcccg_stage", pa.string()),
    pa.field("inpc_grade", pa.string()),
    pa.field("inpc_histologic_group", pa.string()),
    pa.field("inrg_stage", pa.string()),
    pa.field("inss_stage", pa.string()),
    pa.field("international_prognostic_index", pa.string()),
    pa.field("irs_group", pa.string()),
    pa.field("irs_stage", pa.string()),
    pa.field("ishak_fibrosis_score", pa.string()),
    pa.field("iss_stage", pa.string()),
    pa.field("last_known_disease_status", pa.string()),
    pa.field("laterality", pa.string()),
    pa.field("margin_distance", pa.float64()),
    pa.field("margins_involved_site", pa.string()),
    pa.field("masaoka_stage", pa.string()),
    pa.field("max_tumor_bulk_site", pa.string()),
    pa.field("medulloblastoma_molecular_classification", pa.string()),
    pa.field("melanoma_known_primary", pa.string()),
    pa.field("metastasis_at_diagnosis", pa.string()),
    pa.field("method_of_diagnosis", pa.string()),
    pa.field("mitosis_karyorrhexis_index", pa.string()),
    pa.field("morphology", pa.string()),
    pa.field("ovarian_specimen_status", pa.string()),
    pa.field("ovarian_surface_involvement", pa.string()),
    pa.field("pediatric_kidney_staging", pa.string()),
    pa.field("peritoneal_fluid_cytological_status", pa.string()),
    pa.field("primary_diagnosis", pa.string()),
    pa.field("primary_gleason_grade", pa.string()),
    pa.field("prior_malignancy", pa.string()),
    pa.field("prior_treatment", pa.string()),
    pa.field("progression_or_recurrence", pa.string()),
    pa.field("residual_disease", pa.string()),
    pa.field("satellite_nodule_present", pa.string()),
    pa.field("secondary_gleason_grade", pa.string()),
    pa.field("site_of_resection_or_biopsy", pa.string()),
    pa.field("sites_of_involvement", pa.list_(pa.string())),
    pa.field("sites_of_involvement_count", pa.int64()),
    pa.field("supratentorial_localization", pa.string()),
    pa.field("synchronous_malignancy", pa.string()),
    pa.field("tissue_or_organ_of_origin", pa.string()),
    pa.field("tumor_burden", pa.float64()),
    pa.field("tumor_confined_to_organ_of_origin", pa.string()),
    pa.field("tumor_depth", pa.float64()),
    pa.field("tumor_focality", pa.string()),
    pa.field("tumor_grade", pa.string()),
    pa.field("tumor_grade_category", pa.string()),
    pa.field("tumor_of_origin", pa.string()),
    pa.field("tumor_regression_grade", pa.string()),
    pa.field("uicc_clinical_m", pa.string()),
    pa.field("uicc_clinical_n", pa.string()),
    pa.field("uicc_clinical_stage", pa.string()),
    pa.field("uicc_clinical_t", pa.string()),
    pa.field("uicc_pathologic_m", pa.string()),
    pa.field("uicc_pathologic_n", pa.string()),
    pa.field("uicc_pathologic_stage", pa.string()),
    pa.field("uicc_pathologic_t", pa.string()),
    pa.field("uicc_staging_system_edition", pa.string()),
    pa.field("ulceration_indicator", pa.string()),
    pa.field("weiss_assessment_findings", pa.list_(pa.string())),
    pa.field("weiss_assessment_score", pa.string()),
    pa.field("who_cns_grade", pa.string()),
    pa.field("who_nte_grade", pa.string()),
    pa.field("wilms_tumor_histologic_subtype", pa.string()),
    pa.field("year_of_diagnosis", pa.int64()),
    pa.field("treatments", pa.list_(pa.struct(TREATMENT_FIELDS))),
    # Curator notes attached to this diagnosis (GDC `annotations`).
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
    # Disease-specific pathology measurements — 78 fields, nearly all null
    # for any one cancer type since the form is a pan-cancer union.
    pa.field("pathology_details", pa.list_(pa.struct(PATHOLOGY_DETAIL_FIELDS))),
]

FOLLOW_UP_FIELDS: list[pa.Field] = [
    pa.field("follow_up_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("adverse_event", pa.string()),
    pa.field("adverse_event_grade", pa.string()),
    pa.field("barretts_esophagus_goblet_cells_present", pa.string()),
    pa.field("cause_of_response", pa.string()),
    pa.field("days_to_adverse_event", pa.int64()),
    pa.field("days_to_first_event", pa.int64()),
    pa.field("days_to_follow_up", pa.int64()),
    pa.field("days_to_imaging", pa.int64()),
    pa.field("days_to_progression", pa.int64()),
    pa.field("days_to_progression_free", pa.int64()),
    pa.field("days_to_recurrence", pa.int64()),
    pa.field("discontiguous_lesion_count", pa.int64()),
    pa.field("disease_response", pa.string()),
    pa.field("ecog_performance_status", pa.string()),
    pa.field("evidence_of_progression_type", pa.string()),
    pa.field("evidence_of_recurrence_type", pa.string()),
    pa.field("first_event", pa.string()),
    pa.field("histologic_progression", pa.string()),
    pa.field("history_of_tumor", pa.string()),
    pa.field("history_of_tumor_type", pa.string()),
    pa.field("hormone_replacement_therapy_type", pa.string()),
    pa.field("imaging_anatomic_site", pa.list_(pa.string())),
    pa.field("imaging_findings", pa.string()),
    pa.field("imaging_result", pa.string()),
    pa.field("imaging_suv", pa.float64()),
    pa.field("imaging_suv_max", pa.float64()),
    pa.field("imaging_type", pa.string()),
    pa.field("karnofsky_performance_status", pa.string()),
    pa.field("peritoneal_washing_results", pa.string()),
    pa.field("procedures_performed", pa.string()),
    pa.field("progression_or_recurrence", pa.string()),
    pa.field("progression_or_recurrence_anatomic_site", pa.string()),
    pa.field("progression_or_recurrence_type", pa.string()),
    pa.field("recist_targeted_regions_number", pa.int64()),
    pa.field("recist_targeted_regions_sum", pa.float64()),
    pa.field("scan_tracer_used", pa.string()),
    pa.field("timepoint_category", pa.string()),
    pa.field("treatment_emergent_adverse_event", pa.string()),
    pa.field("year_of_follow_up", pa.int64()),
    # Biomarker / molecular assay results recorded at follow-up: IHC stains,
    # FISH translocations, mutation tests. TCGA-CHOL alone has 281 across 51
    # cases, so this is real clinical content rather than a rare edge case.
    pa.field("molecular_tests", pa.list_(pa.struct(MOLECULAR_TEST_FIELDS))),
    # Comorbidities, risk factors, anthropometrics and the disease-specific
    # attributes that have no column on the core follow-up form.
    pa.field(
        "other_clinical_attributes",
        pa.list_(pa.struct(OTHER_CLINICAL_ATTRIBUTE_FIELDS)),
    ),
]

EXPOSURE_FIELDS: list[pa.Field] = [
    pa.field("exposure_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("age_at_last_exposure", pa.int64()),
    pa.field("age_at_onset", pa.int64()),
    pa.field("alcohol_days_per_week", pa.float64()),
    pa.field("alcohol_drinks_per_day", pa.float64()),
    pa.field("alcohol_frequency", pa.string()),
    pa.field("alcohol_history", pa.string()),
    pa.field("alcohol_intensity", pa.string()),
    pa.field("alcohol_type", pa.string()),
    pa.field("asbestos_exposure_type", pa.string()),
    pa.field("chemical_exposure_type", pa.list_(pa.string())),
    pa.field("cigarettes_per_day", pa.float64()),
    pa.field("environmental_tobacco_smoke_exposure", pa.string()),
    pa.field("exposure_duration", pa.string()),
    pa.field("exposure_duration_hrs_per_day", pa.float64()),
    pa.field("exposure_duration_years", pa.int64()),
    pa.field("exposure_source", pa.string()),
    pa.field("exposure_type", pa.string()),
    pa.field("occupation_duration_years", pa.int64()),
    pa.field("occupation_type", pa.list_(pa.string())),
    pa.field("pack_years_smoked", pa.float64()),
    pa.field("parent_with_radiation_exposure", pa.string()),
    pa.field("secondhand_smoke_as_child", pa.string()),
    pa.field("smoking_frequency", pa.string()),
    pa.field("time_between_waking_and_first_smoke", pa.string()),
    pa.field("tobacco_smoking_onset_year", pa.int64()),
    pa.field("tobacco_smoking_quit_year", pa.int64()),
    pa.field("tobacco_smoking_status", pa.string()),
    pa.field("type_of_smoke_exposure", pa.string()),
    pa.field("type_of_tobacco_used", pa.string()),
    pa.field("use_per_day", pa.float64()),
]

FAMILY_HISTORY_FIELDS: list[pa.Field] = [
    pa.field("family_history_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("relationship_age_at_diagnosis", pa.float64()),
    pa.field("relationship_primary_diagnosis", pa.string()),
    pa.field("relationship_sex_at_birth", pa.string()),
    pa.field("relationship_type", pa.string()),
    pa.field("relative_deceased", pa.string()),
    pa.field("relative_smoker", pa.string()),
    pa.field("relative_with_cancer_history", pa.string()),
    pa.field("relatives_with_cancer_history_count", pa.int64()),
]

# ---------------------------------------------------------------------------
# Biospecimen hierarchy: aliquot ⊂ analyte ⊂ portion ⊂ sample
# Preserved verbatim from the GDC dictionary.
# ---------------------------------------------------------------------------

ALIQUOT_FIELDS: list[pa.Field] = [
    pa.field("aliquot_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("aliquot_quantity", pa.float64()),
    pa.field("aliquot_volume", pa.float64()),
    pa.field("amount", pa.float64()),
    pa.field("analyte_type", pa.string()),
    pa.field("centers", pa.string()),
    pa.field("concentration", pa.float64()),
    pa.field("no_matched_normal_low_pass_wgs", pa.bool_()),
    pa.field("no_matched_normal_targeted_sequencing", pa.bool_()),
    pa.field("no_matched_normal_wgs", pa.bool_()),
    pa.field("no_matched_normal_wxs", pa.bool_()),
    pa.field("selected_normal_low_pass_wgs", pa.bool_()),
    pa.field("selected_normal_targeted_sequencing", pa.bool_()),
    pa.field("selected_normal_wgs", pa.bool_()),
    pa.field("selected_normal_wxs", pa.bool_()),
    pa.field("source_center", pa.string()),
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
    # The sequencing / characterization centre that produced this aliquot.
    pa.field("center", pa.struct(CENTER_FIELDS)),
]

ANALYTE_FIELDS: list[pa.Field] = [
    pa.field("analyte_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("a260_a280_ratio", pa.float64()),
    pa.field("amount", pa.float64()),
    pa.field("analyte_quantity", pa.float64()),
    pa.field("analyte_type", pa.string()),  # "DNA" or "RNA" — drives which assays apply
    pa.field("analyte_volume", pa.float64()),
    pa.field("concentration", pa.float64()),
    pa.field("dna_integrity_number", pa.float64()),
    pa.field("experimental_protocol_type", pa.string()),
    pa.field("normal_tumor_genotype_snp_match", pa.string()),
    pa.field("ribosomal_rna_28s_18s_ratio", pa.float64()),
    pa.field("rna_integrity_number", pa.float64()),
    pa.field("spectrophotometer_method", pa.string()),
    pa.field("well_number", pa.string()),
    pa.field("aliquots", pa.list_(pa.struct(ALIQUOT_FIELDS))),
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
]

PORTION_FIELDS: list[pa.Field] = [
    pa.field("portion_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("centers", pa.string()),
    pa.field("creation_datetime", pa.float64()),
    pa.field("is_ffpe", pa.bool_()),  # FFPE-fixed tissue behaves differently in many assays
    pa.field("portion_number", pa.string()),
    pa.field("weight", pa.float64()),
    pa.field("analytes", pa.list_(pa.struct(ANALYTE_FIELDS))),
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
    pa.field("center", pa.struct(CENTER_FIELDS)),
    # Per-slide pathology QC: percent tumour cells, necrosis, lymphocyte
    # infiltration. The GDC-harmonized counterpart of the BCR biotab slide
    # form in `biospecimen_supplement_slide`.
    pa.field("slides", pa.list_(pa.struct(SLIDE_FIELDS))),
]

SAMPLE_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("submitter_id", pa.string()),
    pa.field("biospecimen_anatomic_site", pa.string()),
    pa.field("biospecimen_laterality", pa.string()),
    pa.field("catalog_reference", pa.string()),
    pa.field("current_weight", pa.float64()),
    # days_to_collection: per GDC dictionary, days from index date to BCR
    # receipt of the case's biospecimen package. Per-case batch event (the
    # same value typically applies to all of a case's samples). Can exceed
    # days_to_death because shipping/accession lags death.
    pa.field("days_to_collection", pa.int64()),
    # days_to_sample_procurement: per GDC dictionary, days from index date to
    # the surgical/biopsy event that produced this specific sample. Sparsely
    # populated in TCGA but the right field for true clinical timing.
    pa.field("days_to_sample_procurement", pa.int64()),
    pa.field("diagnosis_pathologically_confirmed", pa.string()),
    pa.field("distance_normal_to_tumor", pa.string()),
    pa.field("distributor_reference", pa.string()),
    pa.field("freezing_method", pa.string()),
    pa.field("growth_rate", pa.int64()),
    pa.field("initial_weight", pa.float64()),
    pa.field("intermediate_dimension", pa.float64()),
    pa.field("longest_dimension", pa.float64()),
    pa.field("method_of_sample_procurement", pa.string()),
    pa.field("parent_samples", pa.string()),
    pa.field("passage_count", pa.int64()),
    pa.field("pathology_report_uuid", pa.string()),
    pa.field("preservation_method", pa.string()),
    pa.field("sample_ordinal", pa.int64()),
    pa.field("sample_type", pa.string()),
    pa.field("shortest_dimension", pa.float64()),
    pa.field("specimen_type", pa.string()),
    pa.field("time_between_clamping_and_freezing", pa.float64()),
    pa.field("time_between_excision_and_freezing", pa.float64()),
    pa.field("tissue_collection_type", pa.string()),
    pa.field("tissue_type", pa.string()),
    pa.field("tumor_descriptor", pa.string()),
    pa.field("portions", pa.list_(pa.struct(PORTION_FIELDS))),
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
]

# ---------------------------------------------------------------------------
# Molecular: Masked Somatic Mutation (MAF) — all 140 columns + 3 FK fields
# ---------------------------------------------------------------------------

# Full GDC MAF v1.0.0 column ordering (140 cols).
_MAF_COLUMNS: list[str] = [
    "Hugo_Symbol",
    "Entrez_Gene_Id",
    "Center",
    "NCBI_Build",
    "Chromosome",
    "Start_Position",
    "End_Position",
    "Strand",
    "Variant_Classification",
    "Variant_Type",
    "Reference_Allele",
    "Tumor_Seq_Allele1",
    "Tumor_Seq_Allele2",
    "dbSNP_RS",
    "dbSNP_Val_Status",
    "Tumor_Sample_Barcode",
    "Matched_Norm_Sample_Barcode",
    "Match_Norm_Seq_Allele1",
    "Match_Norm_Seq_Allele2",
    "Tumor_Validation_Allele1",
    "Tumor_Validation_Allele2",
    "Match_Norm_Validation_Allele1",
    "Match_Norm_Validation_Allele2",
    "Verification_Status",
    "Validation_Status",
    "Mutation_Status",
    "Sequencing_Phase",
    "Sequence_Source",
    "Validation_Method",
    "Score",
    "BAM_File",
    "Sequencer",
    # Despite the names, *_Sample_UUID columns are *aliquot* UUIDs per GDC spec.
    "Tumor_Sample_UUID",
    "Matched_Norm_Sample_UUID",
    "HGVSc",
    "HGVSp",
    "HGVSp_Short",
    "Transcript_ID",
    "Exon_Number",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "all_effects",
    "Allele",
    "Gene",
    "Feature",
    "Feature_type",
    "One_Consequence",
    "Consequence",
    "cDNA_position",
    "CDS_position",
    "Protein_position",
    "Amino_acids",
    "Codons",
    "Existing_variation",
    "DISTANCE",
    "TRANSCRIPT_STRAND",
    "SYMBOL",
    "SYMBOL_SOURCE",
    "HGNC_ID",
    "BIOTYPE",
    "CANONICAL",
    "CCDS",
    "ENSP",
    "SWISSPROT",
    "TREMBL",
    "UNIPARC",
    "UNIPROT_ISOFORM",
    "RefSeq",
    "MANE",
    "APPRIS",
    "FLAGS",
    "SIFT",
    "PolyPhen",
    "EXON",
    "INTRON",
    "DOMAINS",
    "1000G_AF",
    "1000G_AFR_AF",
    "1000G_AMR_AF",
    "1000G_EAS_AF",
    "1000G_EUR_AF",
    "1000G_SAS_AF",
    "ESP_AA_AF",
    "ESP_EA_AF",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "MAX_AF",
    "MAX_AF_POPS",
    "gnomAD_non_cancer_AF",
    "gnomAD_non_cancer_AFR_AF",
    "gnomAD_non_cancer_AMI_AF",
    "gnomAD_non_cancer_AMR_AF",
    "gnomAD_non_cancer_ASJ_AF",
    "gnomAD_non_cancer_EAS_AF",
    "gnomAD_non_cancer_FIN_AF",
    "gnomAD_non_cancer_MID_AF",
    "gnomAD_non_cancer_NFE_AF",
    "gnomAD_non_cancer_OTH_AF",
    "gnomAD_non_cancer_SAS_AF",
    "gnomAD_non_cancer_MAX_AF_adj",
    "gnomAD_non_cancer_MAX_AF_POPS_adj",
    "CLIN_SIG",
    "SOMATIC",
    "PUBMED",
    "TRANSCRIPTION_FACTORS",
    "MOTIF_NAME",
    "MOTIF_POS",
    "HIGH_INF_POS",
    "MOTIF_SCORE_CHANGE",
    "miRNA",
    "IMPACT",
    "PICK",
    "VARIANT_CLASS",
    "TSL",
    "HGVS_OFFSET",
    "PHENO",
    "GENE_PHENO",
    "CONTEXT",
    "tumor_bam_uuid",
    "normal_bam_uuid",
    "case_id",
    "GDC_FILTER",
    "COSMIC",
    "hotspot",
    "RNA_Support",
    "RNA_depth",
    "RNA_ref_count",
    "RNA_alt_count",
    "callers",
]
assert len(_MAF_COLUMNS) == 140, f"expected 140 MAF columns, got {len(_MAF_COLUMNS)}"

_MAF_INT_COLS: set[str] = {
    "Entrez_Gene_Id",
    "Start_Position",
    "End_Position",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "RNA_depth",
    "RNA_ref_count",
    "RNA_alt_count",
}
_MAF_FLOAT_COLS: set[str] = {
    "1000G_AF",
    "1000G_AFR_AF",
    "1000G_AMR_AF",
    "1000G_EAS_AF",
    "1000G_EUR_AF",
    "1000G_SAS_AF",
    "ESP_AA_AF",
    "ESP_EA_AF",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "MAX_AF",
    "gnomAD_non_cancer_AF",
    "gnomAD_non_cancer_AFR_AF",
    "gnomAD_non_cancer_AMI_AF",
    "gnomAD_non_cancer_AMR_AF",
    "gnomAD_non_cancer_ASJ_AF",
    "gnomAD_non_cancer_EAS_AF",
    "gnomAD_non_cancer_FIN_AF",
    "gnomAD_non_cancer_MID_AF",
    "gnomAD_non_cancer_NFE_AF",
    "gnomAD_non_cancer_OTH_AF",
    "gnomAD_non_cancer_SAS_AF",
    "gnomAD_non_cancer_MAX_AF_adj",
    "MOTIF_SCORE_CHANGE",
}


def _maf_field(name: str) -> pa.Field:
    if name in _MAF_INT_COLS:
        return pa.field(name, pa.int64())
    if name in _MAF_FLOAT_COLS:
        return pa.field(name, pa.float64())
    return pa.field(name, pa.string())


# Three sample/aliquot FK fields prepended; all 140 MAF columns follow in MAF
# order. The MAF already carries case_id (col 132) and the aliquot UUIDs
# (Tumor_Sample_UUID, Matched_Norm_Sample_UUID) — we don't duplicate those.
MUTATION_FIELDS: list[pa.Field] = [
    pa.field("tumor_sample_id", pa.string()),
    pa.field("matched_normal_sample_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    *[_maf_field(name) for name in _MAF_COLUMNS],
]

# ---------------------------------------------------------------------------
# Molecular: Gene Expression Quantification (RNA-Seq STAR counts)
# Struct-of-arrays inside list-of-struct; field names match GDC TSV columns.
# stranded_first/stranded_second dropped — the GDC pipeline treats all reads
# as unstranded for cross-sample harmonization (see expression.py docstring).
# ---------------------------------------------------------------------------

EXPRESSION_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    # QC summary metrics (lifted from N_* rows; using unstranded counts)
    pa.field("N_unmapped", pa.int64()),
    pa.field("N_multimapping", pa.int64()),
    pa.field("N_noFeature", pa.int64()),
    pa.field("N_ambiguous", pa.int64()),
    # Gene metadata — GENCODE v36, version suffix preserved (e.g. ENSG...15)
    pa.field("gene_id", pa.list_(pa.string())),
    pa.field("gene_name", pa.list_(pa.string())),
    pa.field("gene_type", pa.list_(pa.string())),
    # Numeric value arrays — index-aligned to gene_id
    pa.field("unstranded", pa.list_(pa.int64())),
    pa.field("tpm_unstranded", pa.list_(pa.float64())),
    pa.field("fpkm_unstranded", pa.list_(pa.float64())),
    pa.field("fpkm_uq_unstranded", pa.list_(pa.float64())),
]

# ---------------------------------------------------------------------------
# Clinical: Pathology Report (the BCR-scanned PDF, shipped verbatim)
#
# Unlike every other modality here, the payload is not a parsed table — it's
# the source document itself. TCGA pathology reports are scanned PDFs; GDC
# ships them open-access with patient identifiers redacted out of the page
# image. We carry the bytes unmodified in `pdf_bytes` rather than a text
# extraction, because any parse is a lossy, tool-and-version-specific
# derivation that consumers should be able to redo (and disagree with)
# without re-downloading 2.6 GB from GDC. A canonical parse, if we add one,
# belongs in its own clearly-labeled column alongside these bytes.
#
# `pathology_report_uuid` is parsed out of the GDC file name
# (`<case_submitter_id>.<REPORT_UUID>.PDF`) and is the same value the GDC
# already reports on `sample.pathology_report_uuid` — so a report joins to
# its sample through a key the dataset has always carried.
# ---------------------------------------------------------------------------

PATHOLOGY_REPORT_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    # Matches `sample.pathology_report_uuid` in SAMPLE_FIELDS.
    pa.field("pathology_report_uuid", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("file_name", pa.string()),
    pa.field("file_size", pa.int64()),
    pa.field("md5sum", pa.string()),
    # The PDF exactly as GDC serves it. Stored as parquet BYTE_ARRAY rather
    # than a base64 string: on this corpus binary+snappy lands at 0.92x the
    # raw bytes where base64+snappy is 1.26x, and `datasets` surfaces it as
    # Value("binary") either way.
    pa.field("pdf_bytes", pa.binary()),
]

# ---------------------------------------------------------------------------
# Derived: ssGSEA pathway activity, one record per scored RNA-Seq aliquot
#
# Struct-of-arrays, mirroring EXPRESSION_FIELDS: the consolidated layout
# already stores per-aliquot vectors that way, and it keeps a patient row to
# one record per aliquot per collection rather than one per (aliquot,
# pathway). `pathway` and the value arrays are index-aligned.
#
# The tabular layout's flat `ssgsea_scores_<collection>` table is the same
# numbers unpivoted; see that schema for why only the raw score is stored.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Copy number / miRNA / protein, consolidated-row shape
#
# Struct-of-arrays, matching EXPRESSION_FIELDS: one record per source file,
# with the per-measurement columns as index-aligned arrays inside it. That
# keeps a patient row at one struct per assay run rather than thousands of
# tiny structs, and lets a consumer column-project a single measurement
# vector without materializing the rest.
#
# These carry fewer FK columns than their tabular counterparts on purpose.
# The consolidated row already holds the full `samples` tree, so submitter
# ids and sample types are one lookup away; the tabular tables have no such
# neighbour and must denormalize.
# ---------------------------------------------------------------------------

# ASCAT is a paired caller and all three of its workflows ship for
# overlapping aliquots, so a case can carry several records for the same
# tumour aliquot. `workflow_type` is scalar here — one record per (aliquot,
# workflow) — which makes "give me the ASCAT3 calls" a filter on the struct
# rather than a filter inside the arrays.
ALLELE_SPECIFIC_CNV_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_id", pa.string()),
    # "ASCAT2" | "ASCAT3" | "AscatNGS".
    pa.field("workflow_type", pa.string()),
    # "Genotyping Array" for ASCAT2 / ASCAT3, "WGS" for AscatNGS.
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # `chr`-prefixed ("chr1"), unlike the masked segments below.
    pa.field("chromosome", pa.list_(pa.string())),
    pa.field("start", pa.list_(pa.int64())),
    pa.field("end", pa.list_(pa.int64())),
    pa.field("copy_number", pa.list_(pa.int32())),
    pa.field("major_copy_number", pa.list_(pa.int32())),
    pa.field("minor_copy_number", pa.list_(pa.int32())),
]

# DNAcopy log2 ratios against a diploid reference, germline CNVs masked.
# Relative, not absolute — see the dataset card for why this and the
# allele-specific calls are not interchangeable.
MASKED_CNV_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("workflow_type", pa.string()),
    pa.field("source_file_id", pa.string()),
    # Bare chromosome names ("1"), unlike the allele-specific segments.
    pa.field("chromosome", pa.list_(pa.string())),
    pa.field("start", pa.list_(pa.int64())),
    pa.field("end", pa.list_(pa.int64())),
    pa.field("num_probes", pa.list_(pa.int32())),
    pa.field("segment_mean", pa.list_(pa.float64())),
]

MIRNA_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("mirna_id", pa.list_(pa.string())),
    pa.field("read_count", pa.list_(pa.int64())),
    pa.field("reads_per_million_mirna_mapped", pa.list_(pa.float64())),
    # "Y" where reads also aligned elsewhere, so the count is not uniquely
    # attributable. Source header is `cross-mapped`.
    pa.field("cross_mapped", pa.list_(pa.string())),
]

# RPPA attaches to a portion rather than an aliquot — the only modality in
# this dataset that does — so it carries `portion_id` where its siblings
# carry `aliquot_id`.
PROTEIN_EXPRESSION_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("portion_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("agid", pa.list_(pa.string())),
    pa.field("lab_id", pa.list_(pa.string())),
    pa.field("catalog_number", pa.list_(pa.string())),
    # Antibody panel version; the panel grew over the project's life.
    pa.field("set_id", pa.list_(pa.string())),
    pa.field("peptide_target", pa.list_(pa.string())),
    # Null entries are the source's literal `NA` — a failed measurement,
    # not a zero.
    pa.field("protein_expression", pa.list_(pa.float64())),
]


SSGSEA_FIELDS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("aliquot_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("pathway", pa.list_(pa.string())),
    pa.field("pathway_url", pa.list_(pa.string())),
    pa.field("matched_gene_count", pa.list_(pa.int32())),
    pa.field("original_gene_count", pa.list_(pa.int32())),
    pa.field("score_raw", pa.list_(pa.float64())),
]


def ssgsea_patient_column(collection: str) -> str:
    return f"samples_ssgsea_{collection}"


# WikiPathways is deliberately absent: its weak sets are miRNA-centric and
# this assay cannot measure miRNAs. See `tcga2hf_pipeline.msigdb`.
SSGSEA_COLLECTIONS: list[str] = [
    "hallmark",
    "reactome",
    "pid",
    "oncogenic",
    "cancer_cell_atlas",
]


# ---------------------------------------------------------------------------
# Top-level patient row
# ---------------------------------------------------------------------------

PATIENT_FIELDS: list[pa.Field] = [
    pa.field("case_id", pa.string()),
    pa.field("case_submitter_id", pa.string()),
    pa.field("project_id", pa.string()),
    # Convenience link to this case's GDC Data Portal page. Templated from
    # case_id at row-build time so the HF dataset viewer renders it as a
    # clickable URL and pandas / polars users get it for free.
    pa.field("gdc_portal_url", pa.string()),
    pa.field("primary_site", pa.string()),
    pa.field("disease_type", pa.string()),
    # GDC `case` entity timeline anchors. index_date names the kind of event
    # used as the day-zero reference (TCGA: nearly always "Diagnosis").
    # All days_to_* fields throughout this row use this anchor.
    pa.field("index_date", pa.string()),
    pa.field("consent_type", pa.string()),
    pa.field("days_to_consent", pa.int64()),
    pa.field("days_to_lost_to_followup", pa.int64()),
    pa.field("lost_to_followup", pa.string()),
    pa.field("demographic", pa.struct(DEMOGRAPHIC_FIELDS)),
    pa.field("diagnoses", pa.list_(pa.struct(DIAGNOSIS_FIELDS))),
    pa.field("follow_ups", pa.list_(pa.struct(FOLLOW_UP_FIELDS))),
    pa.field("exposures", pa.list_(pa.struct(EXPOSURE_FIELDS))),
    pa.field("family_histories", pa.list_(pa.struct(FAMILY_HISTORY_FIELDS))),
    pa.field("samples", pa.list_(pa.struct(SAMPLE_FIELDS))),
    # GDC data_type-named molecular columns. Each is a list of records keyed
    # back to a sample/aliquot via FKs in the struct, so users can fetch
    # only the modalities they want via top-level Parquet column projection.
    pa.field("samples_masked_somatic_mutation", pa.list_(pa.struct(MUTATION_FIELDS))),
    pa.field(
        "samples_gene_expression_quantification",
        pa.list_(pa.struct(EXPRESSION_FIELDS)),
    ),
    pa.field("samples_pathology_report", pa.list_(pa.struct(PATHOLOGY_REPORT_FIELDS))),
    pa.field(
        "samples_allele_specific_copy_number_segment",
        pa.list_(pa.struct(ALLELE_SPECIFIC_CNV_FIELDS)),
    ),
    pa.field(
        "samples_masked_copy_number_segment",
        pa.list_(pa.struct(MASKED_CNV_FIELDS)),
    ),
    pa.field(
        "samples_mirna_expression_quantification",
        pa.list_(pa.struct(MIRNA_FIELDS)),
    ),
    pa.field(
        "samples_protein_expression_quantification",
        pa.list_(pa.struct(PROTEIN_EXPRESSION_FIELDS)),
    ),
    # One column per MSigDB collection, so a consumer can project just the
    # collection they need. Generated below from SSGSEA_COLLECTIONS, which
    # is defined after this list.
    # Survival endpoints — re-derived from the current GDC data using the
    # algorithm published by Liu et al. 2018 (Cell, TCGA Pan-Cancer Clinical
    # Data Resource). Implementation in `tcga2hf_pipeline.survival`;
    # validation against Liu's curated 2018 CDR workbook lives in
    # `dev_research/liu_2018/report.html`.
    #
    # Why we don't ship Liu's curated 2018 values directly: the CDR is a
    # frozen 2018 snapshot derived from a since-modified GDC release. Baking
    # those values into this dataset would lock in irreproducible source
    # drift. Re-deriving on every build keeps these values reproducible
    # from the dataset's other tables alone. Headline agreement against
    # Liu's CDR (both NA OR populated within 30 days): OS 98.2%, DSS 93.2%,
    # PFI 96.3%, DFI 90.1%.
    #
    # Sub-field semantics: `*_event` is 0/1 (event observed vs censored),
    # `*_time` is days from `index_date` (TCGA: diagnosis date). DFI is
    # null for SKCM / THYM / UVM / LAML — Liu specifies no DFI for those
    # tumor types.
    pa.field("survival_derived", pa.struct([
        pa.field("os_event", pa.int64()),
        pa.field("os_time", pa.float64()),
        pa.field("dss_event", pa.int64()),
        pa.field("dss_time", pa.float64()),
        pa.field("pfi_event", pa.int64()),
        pa.field("pfi_time", pa.float64()),
        pa.field("dfi_event", pa.int64()),
        pa.field("dfi_time", pa.float64()),
    ])),
    # Case-level curator annotations — the QC flags that say a case was
    # redacted, has a prior malignancy, or is otherwise "do not use".
    pa.field("annotations", pa.list_(pa.struct(ANNOTATION_FIELDS))),
    # The BCR that contributed the specimen; `code` is the 2-character site
    # in every TCGA barcode ("4G" -> Sapienza University of Rome).
    pa.field("tissue_source_site", pa.struct(TISSUE_SOURCE_SITE_FIELDS)),
    pa.field("program", pa.struct(PROGRAM_FIELDS)),
    # GDC's own file tallies for this case, across every data category and
    # experimental strategy it holds — including the controlled-access and
    # image files this dataset does not carry.
    pa.field(
        "summary",
        pa.struct(
            [
                pa.field("file_count", pa.int64()),
                pa.field("file_size", pa.int64()),
                pa.field(
                    "data_categories",
                    pa.list_(
                        pa.struct(
                            [
                                pa.field("data_category", pa.string()),
                                pa.field("file_count", pa.int64()),
                            ]
                        )
                    ),
                ),
                pa.field(
                    "experimental_strategies",
                    pa.list_(
                        pa.struct(
                            [
                                pa.field("experimental_strategy", pa.string()),
                                pa.field("file_count", pa.int64()),
                            ]
                        )
                    ),
                ),
            ]
        ),
    ),
]

# ssGSEA columns are appended after SSGSEA_COLLECTIONS is declared (below),
# so PATIENT_FIELDS stays the single ordered source of truth for the row.
def _append_ssgsea_patient_fields() -> None:
    for _collection in SSGSEA_COLLECTIONS:
        PATIENT_FIELDS.append(
            pa.field(ssgsea_patient_column(_collection), pa.list_(pa.struct(SSGSEA_FIELDS)))
        )


# Sub-fields of the `survival_derived` struct. Single source of truth for
# the new tabular `survival_derived` table (FK + one row per patient) and
# for `survival.attach_survival` to enumerate when populating both layouts.
SURVIVAL_DERIVED_FIELDS: list[pa.Field] = [
    f for f in next(f.type for f in PATIENT_FIELDS if f.name == "survival_derived")
]


# ---------------------------------------------------------------------------
# Tabular-dataset schemas (one row per GDC entity, one row per source-TSV row)
#
# Companion to the consolidated PATIENT_FIELDS layout. Same source data,
# decomposed into per-entity flat tables. FK columns (`case_id` etc.) are
# prepended to every child table so a user can join with a single key; we
# also pair every UUID FK with its `*_submitter_id` so HF Data Studio rows
# show human-readable values without needing extra joins.
#
# Built by `tcga2hf-pipeline build-tabular` and published to a separate
# HF dataset (`gabrielaltay/tcga-tabular-open`).
# ---------------------------------------------------------------------------


# Reusable FK blocks for the flat molecular tables.
_CASE_FKS: list[pa.Field] = [
    pa.field("case_id", pa.string()),
    pa.field("case_submitter_id", pa.string()),
]
_ALIQUOT_FKS: list[pa.Field] = [
    pa.field("aliquot_id", pa.string()),
    pa.field("aliquot_submitter_id", pa.string()),
]


# Cases: one row per patient with the GDC `cases.json` structure preserved.
# Mirrors PATIENT_FIELDS minus every molecular column (each of those has
# its own flat table below). Each top-level JSON key in the GDC `/cases`
# response maps to one column here — scalars stay scalar, struct fields
# stay struct, list-of-struct fields stay list-of-struct. The table name
# `cases` matches the source file name (`cases.json`).
#
# Derived by exclusion rather than by listing what to keep, so a new
# clinical field added to PATIENT_FIELDS reaches the `cases` table
# automatically. The cost is that a new *molecular* column must be named
# here too, or it would leak into `cases` and duplicate its own table —
# `test_cases_table_excludes_every_molecular_column` guards that.
_MOLECULAR_PATIENT_COLUMNS: set[str] = {
    "samples_masked_somatic_mutation",
    "samples_gene_expression_quantification",
    "samples_pathology_report",
    "samples_allele_specific_copy_number_segment",
    "samples_masked_copy_number_segment",
    "samples_mirna_expression_quantification",
    "samples_protein_expression_quantification",
    *(ssgsea_patient_column(c) for c in SSGSEA_COLLECTIONS),
}

TABULAR_CASES_FIELDS: list[pa.Field] = [
    f for f in PATIENT_FIELDS if f.name not in _MOLECULAR_PATIENT_COLUMNS
]

# Mutations: MUTATION_FIELDS already carries `case_id` (column 132 of the
# MAF), `tumor_sample_id`, `matched_normal_sample_id`, `source_file_id`. We
# prepend `case_submitter_id` for browseability and otherwise ship the MAF
# verbatim — same shape as the consolidated dataset's nested struct, just
# emitted as one row per variant.
TABULAR_MUTATIONS_FIELDS: list[pa.Field] = [
    pa.field("case_submitter_id", pa.string()),
    *MUTATION_FIELDS,
]

# Expression: one row per source-TSV row (4 N_* QC rows + ~60660 gene rows
# per aliquot), with all original TSV columns preserved verbatim. Notably
# keeps `stranded_first` / `stranded_second` (the consolidated dataset
# drops them per GDC's harmonization choice; the tabular dataset is closer
# to the source and includes them).
TABULAR_EXPRESSION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    # Join key into `gene_model`. `gene_name` and `gene_type` are NOT
    # repeated here: they are the same 60,660 values in every aliquot's TSV,
    # and together they cost 487 MB of TCGA-BRCA's 1.88 GiB expression table
    # — more than every count and normalized-value column combined. They
    # live once in `gene_model` instead, and the source TSV is exactly
    # reconstructible by joining on `gene_id`.
    pa.field("gene_id", pa.string()),
    pa.field("unstranded", pa.int64()),
    pa.field("stranded_first", pa.int64()),
    pa.field("stranded_second", pa.int64()),
    pa.field("tpm_unstranded", pa.float64()),
    pa.field("fpkm_unstranded", pa.float64()),
    pa.field("fpkm_uq_unstranded", pa.float64()),
]

# Files: provenance table from each project's modality manifest.json.
# One row per (file_id, case_id) — most files are 1:1 with cases for these
# modalities, but a file can in principle reference multiple cases.
TABULAR_FILES_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    pa.field("file_id", pa.string()),
    pa.field("file_name", pa.string()),
    pa.field("file_size", pa.int64()),
    pa.field("md5sum", pa.string()),
    pa.field("data_category", pa.string()),
    pa.field("data_type", pa.string()),
    pa.field("data_format", pa.string()),
    pa.field("experimental_strategy", pa.string()),
    pa.field("workflow_type", pa.string()),
    pa.field("access", pa.string()),
    # Per-file version provenance from GDC's /files/versions. `gdc_version`
    # is the file's own version and `gdc_first_release` the GDC release it
    # first appeared in — together they identify the bytes independently of
    # which release we happened to fetch at (the API only serves the
    # current one). `gdc_superseded` is true when GDC has since replaced
    # this file with a newer version under a different id.
    pa.field("gdc_version", pa.string()),
    pa.field("gdc_first_release", pa.string()),
    pa.field("gdc_superseded", pa.bool_()),
    pa.field("platform", pa.string()),
    # Local label naming the project subdir the file came from
    # (`mutations` / `expression` / ...). Null for files this pipeline never
    # downloaded.
    pa.field("modality", pa.string()),
    # Every open-access file GDC holds for the project gets a row here,
    # including the ones this dataset does not carry. That makes the table
    # an honest index of the project's whole GDC footprint at negligible
    # cost — TCGA-CHOL's 110 whole-slide images are 88.6 GiB of bytes but
    # 110 rows of index.
    #
    # `in_dataset` means "this file's content is in a published table", not
    # "we downloaded it". The per-case BCR XML supplements are downloaded
    # but deliberately unpublished — they are a second serialization of the
    # biotab data, verified value-for-value — so they are False here.
    pa.field("in_dataset", pa.bool_()),
    # Which table carries it, or null when `in_dataset` is false. A `*`
    # suffix denotes a family of per-form tables (`clinical_supplement_*`).
    pa.field("dataset_table", pa.string()),
    # Populated on every row, present or absent: it is how you fetch what
    # this dataset omits, and how you re-verify what it includes.
    pa.field("gdc_download_url", pa.string()),
]


# Survival endpoints (one row per patient) — flat view of the
# `survival_derived` struct from PATIENT_FIELDS. Same eight values; this
# layout suits the tabular dataset's SQL-friendly purpose so users can
# `SELECT case_submitter_id, os_event, os_time FROM survival_derived`
# without unnesting. Provenance / methodology lives in the `survival_derived`
# field comment in PATIENT_FIELDS above.
TABULAR_SURVIVAL_DERIVED_FIELDS: list[pa.Field] = [
    pa.field("case_submitter_id", pa.string()),
    *SURVIVAL_DERIVED_FIELDS,
]


# Pathology reports: one row per report PDF. Reports are near-1:1 with cases
# pan-TCGA (11,208 reports / 11,121 cases), so this table stays small in row
# count and large only in bytes.
TABULAR_PATHOLOGY_REPORT_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *PATHOLOGY_REPORT_FIELDS,
]


# Sample-level FKs carried on the per-aliquot molecular tables. `sample_type`
# is denormalized alongside the ids for the same reason it is on the ssGSEA
# scores table: tumor-vs-normal is the dominant filter on every molecular
# measurement, and recovering it otherwise means unnesting `cases.samples`.
_SAMPLE_FKS: list[pa.Field] = [
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    pa.field("sample_type", pa.string()),
]


# Copy number, segment level — the two data types GDC serves for TCGA.
#
# Column names are lowercased from the source headers (`Copy_Number` ->
# `copy_number`, `Num_Probes` -> `num_probes`). The seg files are not a
# published spec the way MAF is, their own capitalisation is inconsistent
# between the two types, and lowercase keeps the columns usable as bare SQL
# identifiers. Values are untouched.
#
# Deliberately absent: `Gene Level Copy Number`. GDC serves it as the same
# calls projected onto GENCODE v36, at 34 GB per workflow, and the
# projection is exactly reproducible from `allele_specific_copy_number_segment`
# — so it is a derivation to add later, not source data we are missing.

# ASCAT is a paired caller, so each file names two aliquots. The tumour one
# is identified positively — it is the aliquot the file's own `GDC_Aliquot`
# column reports — rather than by reading sample-type digits out of a
# barcode. The other associated aliquot is the matched normal.
#
# `workflow_type` is a first-class column here, not provenance trivia.
# ASCAT2, ASCAT3 and AscatNGS all ship for overlapping aliquots, and each
# fits purity and ploidy independently, so they can disagree — on TCGA-CHOL
# ASCAT2 and ASCAT3 give the same length-weighted modal copy number for
# 33 of 36 shared aliquots, and where they differ they differ substantially
# (one aliquot is modal 2 under ASCAT2 and modal 4 under ASCAT3). ASCAT3
# also segments more coarsely: 2,469 segments against ASCAT2's 6,580 over
# the same aliquots. A query that does not filter on `workflow_type` is
# pooling three different answers to the same question.
TABULAR_ALLELE_SPECIFIC_CNV_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("matched_normal_aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_submitter_id", pa.string()),
    # "ASCAT2" | "ASCAT3" | "AscatNGS".
    pa.field("workflow_type", pa.string()),
    # "Genotyping Array" for ASCAT2 / ASCAT3, "WGS" for AscatNGS.
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # `chr`-prefixed in this data type ("chr1"), bare in the masked segments
    # ("1"). Carried as each file writes it; see the dataset card.
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
    # Total integer copy number, and its split into the major and minor
    # allele. minor == 0 with major > 0 is loss of heterozygosity.
    pa.field("copy_number", pa.int32()),
    pa.field("major_copy_number", pa.int32()),
    pa.field("minor_copy_number", pa.int32()),
]

# DNAcopy circular-binary-segmentation output with germline CNVs masked out.
# Unlike the allele-specific type this is a *relative* measurement:
# `segment_mean` is log2(sample / reference), so 0 is copy-neutral and there
# is no integer call and no allelic split.
#
# The two types agree in direction but are not interchangeable, and the gap
# is informative rather than noise. Nesting each masked segment inside its
# containing ASCAT3 segment on TCGA-CHOL (2,590 pairs) gives Spearman +0.56,
# with median `segment_mean` rising monotonically across integer copy number
# (CN 0 -> -1.93, CN 1 -> -0.44, CN 2 -> +0.07, CN 4 -> +0.22, CN 8 -> +1.25).
# The correlation is only moderate because ASCAT corrects for tumour purity
# and ploidy while DNAcopy's ratio is against a diploid reference: in a
# hyperdiploid tumour, integer CN 3 is copy-neutral relative to its own
# baseline but still reads near log2 0 here. Use the allele-specific calls
# for absolute copy number, the masked segments for reference-relative ratio.
TABULAR_MASKED_CNV_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("workflow_type", pa.string()),
    pa.field("source_file_id", pa.string()),
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
    # Array probes supporting the segment — the segment's evidence weight.
    pa.field("num_probes", pa.int32()),
    pa.field("segment_mean", pa.float64()),
]


# The unmasked segments — the third and fourth of the GDC's four open copy
# number data types, and the pair that completes source parity.
#
# Two workflows share this table, distinguished by `workflow_type`, because
# they answer the same question with the same six columns:
#
#   - **DNAcopy** covers exactly the aliquots `masked_copy_number_segment`
#     covers (22,629 files either way). The only difference is that the
#     germline CNV segments are still present, so the two tables diffed
#     against each other *are* the mask.
#   - **GATK4 CNV** is WGS read-depth rather than array intensity, over
#     aliquots the genotyping arrays never touched — on TCGA-CHOL its 98
#     aliquots do not intersect the array-based 85 at all. It is new
#     coverage, not a second opinion on existing coverage.
#
# They are not interchangeable despite the shared columns: `num_probes`
# counts array probes for DNAcopy and sequencing bins for GATK4, so the
# evidence weight is only comparable within a workflow. GATK4 is a paired
# caller and carries the matched normal; DNAcopy is single-aliquot and
# leaves those two columns null.
TABULAR_COPY_NUMBER_SEGMENT_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    # GATK4 CNV only; null for the single-aliquot DNAcopy files.
    pa.field("matched_normal_aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_submitter_id", pa.string()),
    # "DNAcopy" | "GATK4 CNV".
    pa.field("workflow_type", pa.string()),
    # "Genotyping Array" for DNAcopy, "WGS" for GATK4 CNV.
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # Bare names ("1") from DNAcopy, `chr`-prefixed ("chr1") from GATK4 CNV.
    # Carried as each file writes it, matching the two segment tables above.
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
    # Array probes (DNAcopy) or sequencing bins (GATK4 CNV) — see above.
    pa.field("num_probes", pa.int32()),
    pa.field("segment_mean", pa.float64()),
]


# Copy number projected onto the GENCODE v36 gene model, all four callers.
#
# `gene_name`, `chromosome`, `start` and `end` are deliberately NOT repeated
# here — they are identical in all 33,902 source files and live once in
# `gene_model`, joined on `gene_id`. That is the single biggest size lever
# in the layout: the GDC ships this data type as 3,350 KB of TSV per
# aliquot, of which the gene model is the overwhelming majority.
#
# Why this table exists at all, given that we already publish the segments:
#
#   - ASCAT2 / ASCAT3 / AscatNGS gene-level values are exactly reproducible
#     by projecting `allele_specific_copy_number_segment` onto the gene
#     model (verified on TCGA-CHOL: zero mismatches over 3 aliquots and
#     180k genes, with min/max copy number for boundary-spanning genes
#     recovered as the min/max over overlapping segments). They are here for
#     source parity, not because they add information.
#   - **ABSOLUTE LiftOver does add information.** It ships no segment file
#     anywhere in the GDC, so its purity- and ploidy-corrected absolute copy
#     number exists at gene level or not at all. It is also the only
#     workflow here whose files name a single aliquot; the three ASCAT
#     workflows are paired and name two.
#
# The three ASCAT workflows leave `min_copy_number` / `max_copy_number` equal
# to `copy_number` except where a gene straddles a segment boundary. Genes on
# chrM are absent from every file — the copy number callers exclude the
# mitochondrial genome — so 37 of `gene_model`'s 60,660 genes never appear.
TABULAR_GENE_LEVEL_CNV_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    # ASCAT is paired; ABSOLUTE LiftOver is not and leaves these null.
    pa.field("matched_normal_aliquot_id", pa.string()),
    pa.field("matched_normal_aliquot_submitter_id", pa.string()),
    # "ASCAT2" | "ASCAT3" | "AscatNGS" | "ABSOLUTE LiftOver".
    pa.field("workflow_type", pa.string()),
    pa.field("experimental_strategy", pa.string()),
    pa.field("source_file_id", pa.string()),
    # Join key into `gene_model`.
    pa.field("gene_id", pa.string()),
    # Null where the caller made no call for the gene (6,117 of 60,623 genes
    # in a typical ABSOLUTE file, ~800 in an ASCAT3 one).
    pa.field("copy_number", pa.int32()),
    pa.field("min_copy_number", pa.int32()),
    pa.field("max_copy_number", pa.int32()),
]


# SeSAMe level-3 methylation betas, one row per (aliquot, probe).
#
# The source is a headerless two-column TXT — probe id and beta — so unlike
# expression and gene-level copy number there is no repeated annotation to
# normalize away: GDC ships no probe coordinates, no gene mapping, nothing
# but the two columns. `probe_id` therefore stays, and the only lever on
# size is row-group sizing against the ~486k probe cardinality.
#
# `platform` is a first-class column, not provenance trivia. TCGA spans
# three array generations with different probe sets — Illumina 450k (9,812
# files), 27k (2,662) and EPIC v2 (53) — and a beta value is only
# comparable to another measured on the same platform. A query that pools
# platforms without saying so is comparing different assays.
#
# Beta is the fraction of methylated signal, in [0, 1]. Nulls are real and
# common (14.6% of probes in a typical 450k file): SeSAMe masks probes it
# cannot trust rather than emitting a number, so a null means "masked", not
# "zero methylation".
TABULAR_METHYLATION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    # "illumina human methylation 450" | "... 27" | "illumina methylation epic v2".
    pa.field("platform", pa.string()),
    pa.field("source_file_id", pa.string()),
    # Illumina probe id: `cg` CpG, `ch` non-CpG, `ct` control, `rs` SNP.
    pa.field("probe_id", pa.string()),
    pa.field("beta_value", pa.float64()),
]


# miRNA isoform-level quantification — one row per (aliquot, isoform).
#
# The per-isoform companion to `mirna_expression_quantification`, from the
# same BCGSC run over the same aliquots: that table gives one number per
# mature miRNA, this one splits it across the distinct read pileups that
# were collapsed into it. Roughly 4,500 isoforms per aliquot against ~1,881
# mature miRNAs.
TABULAR_ISOFORM_EXPRESSION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("mirna_id", pa.string()),
    # Genomic span of the isoform, as written: "hg38:chr9:94175942-94175961:+".
    pa.field("isoform_coords", pa.string()),
    pa.field("read_count", pa.int64()),
    pa.field("reads_per_million_mirna_mapped", pa.float64()),
    # Source header is `cross-mapped`; the hyphen is not a legal SQL
    # identifier, so it is underscored here as it is in the miRNA table.
    pa.field("cross_mapped", pa.string()),
    # "precursor" | "mature,MIMAT..." | "stemloop" | "unannotated" — which
    # part of the hairpin the reads landed on, with the miRBase accession
    # appended where there is one.
    pa.field("mirna_region", pa.string()),
]


# The GENCODE v36 gene model, once per dataset rather than once per row.
#
# Every project dataset carries its own copy so it stays a standalone
# artifact — at 60,660 rows it costs ~1.25 MiB, which is cheaper than any
# cross-dataset dependency would be. It is referenced by `gene_id` from
# `gene_expression_quantification` and `gene_level_copy_number`.
#
# Assembled from the two GDC sources that each carry half of it, so nothing
# here is invented: `gene_name` / `gene_type` come from the STAR expression
# TSVs, `chromosome` / `start` / `end` from the gene-level copy number TSVs.
# The 37 chrM genes appear only in expression, so they carry a `gene_name`
# and `gene_type` but null coordinates rather than coordinates borrowed from
# outside the GDC. Where both sources name a gene they agree exactly
# (verified across all 60,623 shared genes).
TABULAR_GENE_MODEL_FIELDS: list[pa.Field] = [
    pa.field("gene_id", pa.string()),
    pa.field("gene_name", pa.string()),
    # Present only for genes the STAR expression files carry.
    pa.field("gene_type", pa.string()),
    # Null for the 37 chrM genes — see above.
    pa.field("chromosome", pa.string()),
    pa.field("start", pa.int64()),
    pa.field("end", pa.int64()),
]


# miRNA-Seq, one row per (aliquot, miRBase v21 mature miRNA). ~1,881 miRNAs
# per aliquot.
TABULAR_MIRNA_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("mirna_id", pa.string()),
    pa.field("read_count", pa.int64()),
    pa.field("reads_per_million_mirna_mapped", pa.float64()),
    # "Y" when reads for this miRNA also aligned elsewhere in the genome, so
    # its count is not uniquely attributable. GDC ships the flag rather than
    # dropping the row; we do the same.
    pa.field("cross_mapped", pa.string()),
]


# Reverse Phase Protein Array. Unique among our molecular modalities in
# attaching to a *portion* rather than an aliquot, so it carries portion FKs
# and resolves the sample through the portion.
#
# Coverage is the narrowest we ship — 7,827 of 11,428 TCGA cases — because
# RPPA was only run on a subset, and the antibody panel itself grew over the
# project's life (`set_id` distinguishes the panel versions). A peptide
# target absent for a sample may mean "not measured on that panel" rather
# than "measured as zero".
TABULAR_PROTEIN_EXPRESSION_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    *_SAMPLE_FKS,
    pa.field("portion_id", pa.string()),
    pa.field("portion_submitter_id", pa.string()),
    pa.field("source_file_id", pa.string()),
    # MD Anderson's antibody id, stable across panel versions.
    pa.field("agid", pa.string()),
    pa.field("lab_id", pa.string()),
    pa.field("catalog_number", pa.string()),
    # Antibody panel version this measurement came from ("Old", "V1.2", ...).
    pa.field("set_id", pa.string()),
    # The protein or phospho-site, e.g. "AKT_pS473".
    pa.field("peptide_target", pa.string()),
    # Replicate-based normalized log2 signal; centred near 0, sign-meaningful.
    pa.field("protein_expression", pa.float64()),
]


# ssGSEA pathway activity. Two tables per gene-set collection, named
# `ssgsea_scores_<collection>` and `ssgsea_stats_<collection>` — grouping by
# kind rather than by collection so every scores table sorts together in the
# HF config list, and adding a collection is two new tables rather than new
# columns on an existing one (which would rewrite every row).
#
# `score_raw` is deliberately the only score column. GSVA's `normalize=TRUE`
# divides by the range of the entire score matrix, which makes a score depend
# on the cohort and the collection it was computed alongside rather than on
# the sample. Raw scores depend on nothing but their own sample, so they can
# be computed per project, stay valid when projects or collections are added
# later, and still yield the normalized view on demand — the divisor is
# recoverable from the stats table as MAX(max) - MIN(min) over its
# `pan_cancer` rows.

TABULAR_SSGSEA_SCORES_FIELDS: list[pa.Field] = [
    *_CASE_FKS,
    pa.field("sample_id", pa.string()),
    pa.field("sample_submitter_id", pa.string()),
    # Carried despite the expression table not carrying it: tumor-vs-normal
    # is the dominant filter on pathway activity, and recovering it
    # otherwise means unnesting `cases.samples`.
    pa.field("sample_type", pa.string()),
    *_ALIQUOT_FKS,
    pa.field("source_file_id", pa.string()),
    pa.field("pathway", pa.string()),
    # Link to the authoritative MSigDB definition of this gene set, so a
    # consumer can check what a score actually means without leaving the
    # table. Templated from the pathway name (same pattern as
    # `gdc_portal_url`); verified derivable for all 26,937 pathways across
    # the collections we ship.
    pa.field("pathway_url", pa.string()),
    # Per-pathway provenance. Constant within a pathway, so dictionary
    # encoding makes it ~1% of the table, and it lets a consumer filter on
    # gene-set coverage without a join.
    pa.field("matched_gene_count", pa.int32()),
    pa.field("original_gene_count", pa.int32()),
    pa.field("score_raw", pa.float64()),
]

# Reference distributions for turning raw scores into z-scores or GSVA-style
# normalized values. Every value here is derivable from the scores tables by
# aggregation — this is a materialized convenience view, not new evidence.
# Each project ships its own rows *plus* the pan-cancer rows, so a consumer
# who loads one project can still normalize against all of TCGA without
# scanning 33 configs.
TABULAR_SSGSEA_STATS_FIELDS: list[pa.Field] = [
    # "pan_cancer" (every project) or "project" (this project alone).
    pa.field("population", pa.string()),
    # Null on pan_cancer rows.
    pa.field("project_id", pa.string()),
    # Null means every sample type; otherwise the type the row is restricted to.
    pa.field("sample_type", pa.string()),
    pa.field("pathway", pa.string()),
    pa.field("n_aliquots", pa.int64()),
    pa.field("mean", pa.float64()),
    # Sample standard deviation (ddof=1); null when n_aliquots < 2.
    pa.field("sd", pa.float64()),
    pa.field("min", pa.float64()),
    pa.field("q25", pa.float64()),
    pa.field("median", pa.float64()),
    pa.field("q75", pa.float64()),
    pa.field("max", pa.float64()),
]


_append_ssgsea_patient_fields()
PATIENTS = pa.schema(PATIENT_FIELDS)


def ssgsea_scores_table(collection: str) -> str:
    return f"ssgsea_scores_{collection}"


def ssgsea_stats_table(collection: str) -> str:
    return f"ssgsea_stats_{collection}"


# Map of table-name → schema, used by the build-tabular command and the
# dataset card generator. Table names mirror the GDC's stable concepts:
# `cases` (cases.json), `masked_somatic_mutation` and
# `gene_expression_quantification` (snake_cased GDC `data_type` enum
# values), `files` (per-modality manifests, derived from the GDC `/files`
# endpoint). The exception is `survival_derived` — a value-added table
# of re-derived OS / DSS / PFI / DFI endpoints (Liu et al. 2018 algorithm)
# that doesn't correspond to a single GDC concept; provenance is in the
# dataset card's "Survival endpoints" section.
TABULAR_TABLES: dict[str, pa.Schema] = {
    "cases": pa.schema(TABULAR_CASES_FIELDS),
    "masked_somatic_mutation": pa.schema(TABULAR_MUTATIONS_FIELDS),
    "gene_expression_quantification": pa.schema(TABULAR_EXPRESSION_FIELDS),
    "files": pa.schema(TABULAR_FILES_FIELDS),
    "survival_derived": pa.schema(TABULAR_SURVIVAL_DERIVED_FIELDS),
    "pathology_report": pa.schema(TABULAR_PATHOLOGY_REPORT_FIELDS),
    "allele_specific_copy_number_segment": pa.schema(TABULAR_ALLELE_SPECIFIC_CNV_FIELDS),
    "masked_copy_number_segment": pa.schema(TABULAR_MASKED_CNV_FIELDS),
    "copy_number_segment": pa.schema(TABULAR_COPY_NUMBER_SEGMENT_FIELDS),
    "gene_level_copy_number": pa.schema(TABULAR_GENE_LEVEL_CNV_FIELDS),
    "gene_model": pa.schema(TABULAR_GENE_MODEL_FIELDS),
    "methylation_beta_value": pa.schema(TABULAR_METHYLATION_FIELDS),
    "isoform_expression_quantification": pa.schema(TABULAR_ISOFORM_EXPRESSION_FIELDS),
    "mirna_expression_quantification": pa.schema(TABULAR_MIRNA_FIELDS),
    "protein_expression_quantification": pa.schema(TABULAR_PROTEIN_EXPRESSION_FIELDS),
    # One scores + one stats table per gene-set collection. Extending to
    # Reactome or WikiPathways is an entry in SSGSEA_COLLECTIONS; the
    # schemas, emitters and tests are all collection-agnostic.
    **{ssgsea_scores_table(c): pa.schema(TABULAR_SSGSEA_SCORES_FIELDS) for c in SSGSEA_COLLECTIONS},
    **{ssgsea_stats_table(c): pa.schema(TABULAR_SSGSEA_STATS_FIELDS) for c in SSGSEA_COLLECTIONS},
}
